# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1297, 836)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_nbc = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_nbc.setFont(font)
        self.button_nbc.setObjectName("button_nbc")
        self.gridLayout_2.addWidget(self.button_nbc, 3, 5, 1, 1)
        self.label_ceshishuju = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_ceshishuju.setFont(font)
        self.label_ceshishuju.setObjectName("label_ceshishuju")
        self.gridLayout_2.addWidget(self.label_ceshishuju, 0, 4, 1, 1)
        self.button_ann = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_ann.setFont(font)
        self.button_ann.setObjectName("button_ann")
        self.gridLayout_2.addWidget(self.button_ann, 3, 4, 1, 1)
        self.testWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.testWidget.setObjectName("testWidget")
        self.testWidget.setColumnCount(0)
        self.testWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.testWidget, 1, 3, 1, 3)
        self.label_xunlianshuju = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_xunlianshuju.setFont(font)
        self.label_xunlianshuju.setObjectName("label_xunlianshuju")
        self.gridLayout_2.addWidget(self.label_xunlianshuju, 0, 1, 1, 1)
        self.button_dt = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_dt.setFont(font)
        self.button_dt.setObjectName("button_dt")
        self.gridLayout_2.addWidget(self.button_dt, 3, 2, 1, 1)
        self.button_rf = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_rf.setFont(font)
        self.button_rf.setObjectName("button_rf")
        self.gridLayout_2.addWidget(self.button_rf, 3, 3, 1, 1)
        self.button_svm = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_svm.setFont(font)
        self.button_svm.setObjectName("button_svm")
        self.gridLayout_2.addWidget(self.button_svm, 3, 1, 1, 1)
        self.trainWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.trainWidget.setObjectName("trainWidget")
        self.trainWidget.setColumnCount(0)
        self.trainWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.trainWidget, 1, 0, 1, 3)
        self.button_lda = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_lda.setFont(font)
        self.button_lda.setObjectName("button_lda")
        self.gridLayout_2.addWidget(self.button_lda, 3, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_LDA = QtWidgets.QWidget()
        self.page_LDA.setObjectName("page_LDA")
        self.gridLayout = QtWidgets.QGridLayout(self.page_LDA)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_solver_lda = QtWidgets.QLabel(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_solver_lda.setFont(font)
        self.label_solver_lda.setObjectName("label_solver_lda")
        self.horizontalLayout.addWidget(self.label_solver_lda)
        self.comboBox_solver_lda = QtWidgets.QComboBox(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_solver_lda.setFont(font)
        self.comboBox_solver_lda.setObjectName("comboBox_solver_lda")
        self.comboBox_solver_lda.addItem("")
        self.comboBox_solver_lda.addItem("")
        self.comboBox_solver_lda.addItem("")
        self.horizontalLayout.addWidget(self.comboBox_solver_lda)
        self.Pre_Processing_lda = QtWidgets.QRadioButton(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_lda.setFont(font)
        self.Pre_Processing_lda.setChecked(True)
        self.Pre_Processing_lda.setObjectName("Pre_Processing_lda")
        self.horizontalLayout.addWidget(self.Pre_Processing_lda)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.lda_fenleijieguo = QtWidgets.QTableWidget(self.page_LDA)
        self.lda_fenleijieguo.setObjectName("lda_fenleijieguo")
        self.lda_fenleijieguo.setColumnCount(0)
        self.lda_fenleijieguo.setRowCount(0)
        self.gridLayout.addWidget(self.lda_fenleijieguo, 4, 1, 1, 1)
        self.label_report_lda = QtWidgets.QLabel(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_report_lda.setFont(font)
        self.label_report_lda.setObjectName("label_report_lda")
        self.gridLayout.addWidget(self.label_report_lda, 2, 0, 1, 1)
        self.label_fenleijieguo_lda = QtWidgets.QLabel(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_fenleijieguo_lda.setFont(font)
        self.label_fenleijieguo_lda.setObjectName("label_fenleijieguo_lda")
        self.gridLayout.addWidget(self.label_fenleijieguo_lda, 2, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.xunlian_lda = QtWidgets.QPushButton(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_lda.setFont(font)
        self.xunlian_lda.setObjectName("xunlian_lda")
        self.horizontalLayout_2.addWidget(self.xunlian_lda)
        self.baocunmoxing_lda = QtWidgets.QPushButton(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_lda.setFont(font)
        self.baocunmoxing_lda.setObjectName("baocunmoxing_lda")
        self.horizontalLayout_2.addWidget(self.baocunmoxing_lda)
        self.daorumoxing_lda = QtWidgets.QPushButton(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_lda.setFont(font)
        self.daorumoxing_lda.setObjectName("daorumoxing_lda")
        self.horizontalLayout_2.addWidget(self.daorumoxing_lda)
        self.ceshijieguo_lda = QtWidgets.QPushButton(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshijieguo_lda.setFont(font)
        self.ceshijieguo_lda.setObjectName("ceshijieguo_lda")
        self.horizontalLayout_2.addWidget(self.ceshijieguo_lda)
        self.baocunshuju_lda = QtWidgets.QPushButton(self.page_LDA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_lda.setFont(font)
        self.baocunshuju_lda.setObjectName("baocunshuju_lda")
        self.horizontalLayout_2.addWidget(self.baocunshuju_lda)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.lda_clfReport = QtWidgets.QTextBrowser(self.page_LDA)
        self.lda_clfReport.setObjectName("lda_clfReport")
        self.gridLayout.addWidget(self.lda_clfReport, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_LDA)
        self.page_SVM = QtWidgets.QWidget()
        self.page_SVM.setObjectName("page_SVM")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_SVM)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_c_svm = QtWidgets.QLabel(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_c_svm.setFont(font)
        self.label_c_svm.setObjectName("label_c_svm")
        self.horizontalLayout_3.addWidget(self.label_c_svm)
        self.c_svm = QtWidgets.QLineEdit(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.c_svm.setFont(font)
        self.c_svm.setObjectName("c_svm")
        self.horizontalLayout_3.addWidget(self.c_svm)
        self.label_kernel_svm = QtWidgets.QLabel(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_kernel_svm.setFont(font)
        self.label_kernel_svm.setObjectName("label_kernel_svm")
        self.horizontalLayout_3.addWidget(self.label_kernel_svm)
        self.comboBox_kernel_svm = QtWidgets.QComboBox(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_kernel_svm.setFont(font)
        self.comboBox_kernel_svm.setObjectName("comboBox_kernel_svm")
        self.comboBox_kernel_svm.addItem("")
        self.comboBox_kernel_svm.addItem("")
        self.comboBox_kernel_svm.addItem("")
        self.comboBox_kernel_svm.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_kernel_svm)
        self.balanced_svm = QtWidgets.QCheckBox(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.balanced_svm.setFont(font)
        self.balanced_svm.setChecked(False)
        self.balanced_svm.setObjectName("balanced_svm")
        self.horizontalLayout_3.addWidget(self.balanced_svm)
        self.label_decision_svm = QtWidgets.QLabel(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_decision_svm.setFont(font)
        self.label_decision_svm.setObjectName("label_decision_svm")
        self.horizontalLayout_3.addWidget(self.label_decision_svm)
        self.comboBox_decision_svm = QtWidgets.QComboBox(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_decision_svm.setFont(font)
        self.comboBox_decision_svm.setObjectName("comboBox_decision_svm")
        self.comboBox_decision_svm.addItem("")
        self.comboBox_decision_svm.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_decision_svm)
        self.Pre_Processing_svm = QtWidgets.QRadioButton(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_svm.setFont(font)
        self.Pre_Processing_svm.setChecked(True)
        self.Pre_Processing_svm.setObjectName("Pre_Processing_svm")
        self.horizontalLayout_3.addWidget(self.Pre_Processing_svm)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.svm_fenleijieguo = QtWidgets.QTableWidget(self.page_SVM)
        self.svm_fenleijieguo.setObjectName("svm_fenleijieguo")
        self.svm_fenleijieguo.setColumnCount(0)
        self.svm_fenleijieguo.setRowCount(0)
        self.gridLayout_3.addWidget(self.svm_fenleijieguo, 4, 1, 1, 1)
        self.label_report_svm = QtWidgets.QLabel(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_report_svm.setFont(font)
        self.label_report_svm.setObjectName("label_report_svm")
        self.gridLayout_3.addWidget(self.label_report_svm, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.xunlian_svm = QtWidgets.QPushButton(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_svm.setFont(font)
        self.xunlian_svm.setObjectName("xunlian_svm")
        self.horizontalLayout_4.addWidget(self.xunlian_svm)
        self.baocunmoxing_svm = QtWidgets.QPushButton(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_svm.setFont(font)
        self.baocunmoxing_svm.setObjectName("baocunmoxing_svm")
        self.horizontalLayout_4.addWidget(self.baocunmoxing_svm)
        self.daorumoxing_svm = QtWidgets.QPushButton(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_svm.setFont(font)
        self.daorumoxing_svm.setObjectName("daorumoxing_svm")
        self.horizontalLayout_4.addWidget(self.daorumoxing_svm)
        self.ceshijieguo_svm = QtWidgets.QPushButton(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshijieguo_svm.setFont(font)
        self.ceshijieguo_svm.setObjectName("ceshijieguo_svm")
        self.horizontalLayout_4.addWidget(self.ceshijieguo_svm)
        self.baocunshuju_svm = QtWidgets.QPushButton(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_svm.setFont(font)
        self.baocunshuju_svm.setObjectName("baocunshuju_svm")
        self.horizontalLayout_4.addWidget(self.baocunshuju_svm)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.label_fenleijieguo_svm = QtWidgets.QLabel(self.page_SVM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_fenleijieguo_svm.setFont(font)
        self.label_fenleijieguo_svm.setObjectName("label_fenleijieguo_svm")
        self.gridLayout_3.addWidget(self.label_fenleijieguo_svm, 2, 1, 1, 1)
        self.svm_clfReport = QtWidgets.QTextBrowser(self.page_SVM)
        self.svm_clfReport.setObjectName("svm_clfReport")
        self.gridLayout_3.addWidget(self.svm_clfReport, 4, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_SVM)
        self.page_DT = QtWidgets.QWidget()
        self.page_DT.setObjectName("page_DT")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_DT)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.checkBox_maxdep_dt = QtWidgets.QCheckBox(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.checkBox_maxdep_dt.setFont(font)
        self.checkBox_maxdep_dt.setObjectName("checkBox_maxdep_dt")
        self.horizontalLayout_5.addWidget(self.checkBox_maxdep_dt)
        self.maxdep_dt = QtWidgets.QLineEdit(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.maxdep_dt.setFont(font)
        self.maxdep_dt.setObjectName("maxdep_dt")
        self.horizontalLayout_5.addWidget(self.maxdep_dt)
        self.label_minspl_dt = QtWidgets.QLabel(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_minspl_dt.setFont(font)
        self.label_minspl_dt.setObjectName("label_minspl_dt")
        self.horizontalLayout_5.addWidget(self.label_minspl_dt)
        self.minspl_dt = QtWidgets.QLineEdit(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.minspl_dt.setFont(font)
        self.minspl_dt.setObjectName("minspl_dt")
        self.horizontalLayout_5.addWidget(self.minspl_dt)
        self.label_minlea_dt = QtWidgets.QLabel(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_minlea_dt.setFont(font)
        self.label_minlea_dt.setObjectName("label_minlea_dt")
        self.horizontalLayout_5.addWidget(self.label_minlea_dt)
        self.minlea_dt = QtWidgets.QLineEdit(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.minlea_dt.setFont(font)
        self.minlea_dt.setObjectName("minlea_dt")
        self.horizontalLayout_5.addWidget(self.minlea_dt)
        self.checkBox_balanced_dt = QtWidgets.QCheckBox(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.checkBox_balanced_dt.setFont(font)
        self.checkBox_balanced_dt.setObjectName("checkBox_balanced_dt")
        self.horizontalLayout_5.addWidget(self.checkBox_balanced_dt)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 0, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.xunlian_dt = QtWidgets.QPushButton(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_dt.setFont(font)
        self.xunlian_dt.setObjectName("xunlian_dt")
        self.horizontalLayout_6.addWidget(self.xunlian_dt)
        self.baocunmoxing_dt = QtWidgets.QPushButton(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_dt.setFont(font)
        self.baocunmoxing_dt.setObjectName("baocunmoxing_dt")
        self.horizontalLayout_6.addWidget(self.baocunmoxing_dt)
        self.daorumoxing_dt = QtWidgets.QPushButton(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_dt.setFont(font)
        self.daorumoxing_dt.setObjectName("daorumoxing_dt")
        self.horizontalLayout_6.addWidget(self.daorumoxing_dt)
        self.ceshijieguo_dt = QtWidgets.QPushButton(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshijieguo_dt.setFont(font)
        self.ceshijieguo_dt.setObjectName("ceshijieguo_dt")
        self.horizontalLayout_6.addWidget(self.ceshijieguo_dt)
        self.baocunshuju_dt = QtWidgets.QPushButton(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_dt.setFont(font)
        self.baocunshuju_dt.setObjectName("baocunshuju_dt")
        self.horizontalLayout_6.addWidget(self.baocunshuju_dt)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 1, 0, 1, 2)
        self.label_report_dt = QtWidgets.QLabel(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_report_dt.setFont(font)
        self.label_report_dt.setObjectName("label_report_dt")
        self.gridLayout_4.addWidget(self.label_report_dt, 2, 0, 1, 1)
        self.label_fenleijieguo_dt = QtWidgets.QLabel(self.page_DT)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_fenleijieguo_dt.setFont(font)
        self.label_fenleijieguo_dt.setObjectName("label_fenleijieguo_dt")
        self.gridLayout_4.addWidget(self.label_fenleijieguo_dt, 2, 1, 1, 1)
        self.dt_fenleijieguo = QtWidgets.QTableWidget(self.page_DT)
        self.dt_fenleijieguo.setObjectName("dt_fenleijieguo")
        self.dt_fenleijieguo.setColumnCount(0)
        self.dt_fenleijieguo.setRowCount(0)
        self.gridLayout_4.addWidget(self.dt_fenleijieguo, 3, 1, 1, 1)
        self.dt_clfReport = QtWidgets.QTextBrowser(self.page_DT)
        self.dt_clfReport.setObjectName("dt_clfReport")
        self.gridLayout_4.addWidget(self.dt_clfReport, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_DT)
        self.page_RF = QtWidgets.QWidget()
        self.page_RF.setObjectName("page_RF")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_RF)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_numtree_rf = QtWidgets.QLabel(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_numtree_rf.setFont(font)
        self.label_numtree_rf.setObjectName("label_numtree_rf")
        self.horizontalLayout_7.addWidget(self.label_numtree_rf)
        self.numtree_rf = QtWidgets.QLineEdit(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.numtree_rf.setFont(font)
        self.numtree_rf.setObjectName("numtree_rf")
        self.horizontalLayout_7.addWidget(self.numtree_rf)
        self.checkBox_numfea_rf = QtWidgets.QCheckBox(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.checkBox_numfea_rf.setFont(font)
        self.checkBox_numfea_rf.setObjectName("checkBox_numfea_rf")
        self.horizontalLayout_7.addWidget(self.checkBox_numfea_rf)
        self.numfea_rf = QtWidgets.QLineEdit(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.numfea_rf.setFont(font)
        self.numfea_rf.setObjectName("numfea_rf")
        self.horizontalLayout_7.addWidget(self.numfea_rf)
        self.label_weight_rf = QtWidgets.QLabel(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_weight_rf.setFont(font)
        self.label_weight_rf.setObjectName("label_weight_rf")
        self.horizontalLayout_7.addWidget(self.label_weight_rf)
        self.comboBox_weight_rf = QtWidgets.QComboBox(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_weight_rf.setFont(font)
        self.comboBox_weight_rf.setObjectName("comboBox_weight_rf")
        self.comboBox_weight_rf.addItem("")
        self.comboBox_weight_rf.addItem("")
        self.comboBox_weight_rf.addItem("")
        self.horizontalLayout_7.addWidget(self.comboBox_weight_rf)
        self.gridLayout_5.addLayout(self.horizontalLayout_7, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.xunlian_rf = QtWidgets.QPushButton(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_rf.setFont(font)
        self.xunlian_rf.setObjectName("xunlian_rf")
        self.horizontalLayout_8.addWidget(self.xunlian_rf)
        self.baocunmoxing_rf = QtWidgets.QPushButton(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_rf.setFont(font)
        self.baocunmoxing_rf.setObjectName("baocunmoxing_rf")
        self.horizontalLayout_8.addWidget(self.baocunmoxing_rf)
        self.daorumoxing_rf = QtWidgets.QPushButton(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_rf.setFont(font)
        self.daorumoxing_rf.setObjectName("daorumoxing_rf")
        self.horizontalLayout_8.addWidget(self.daorumoxing_rf)
        self.ceshijieguo_rf = QtWidgets.QPushButton(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshijieguo_rf.setFont(font)
        self.ceshijieguo_rf.setObjectName("ceshijieguo_rf")
        self.horizontalLayout_8.addWidget(self.ceshijieguo_rf)
        self.baocunshuju_rf = QtWidgets.QPushButton(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_rf.setFont(font)
        self.baocunshuju_rf.setObjectName("baocunshuju_rf")
        self.horizontalLayout_8.addWidget(self.baocunshuju_rf)
        self.gridLayout_5.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.label_report_rf = QtWidgets.QLabel(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_report_rf.setFont(font)
        self.label_report_rf.setObjectName("label_report_rf")
        self.gridLayout_5.addWidget(self.label_report_rf, 2, 0, 1, 1)
        self.label_fenleijieguo_rf = QtWidgets.QLabel(self.page_RF)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_fenleijieguo_rf.setFont(font)
        self.label_fenleijieguo_rf.setObjectName("label_fenleijieguo_rf")
        self.gridLayout_5.addWidget(self.label_fenleijieguo_rf, 2, 1, 1, 1)
        self.rf_fenleijieguo = QtWidgets.QTableWidget(self.page_RF)
        self.rf_fenleijieguo.setObjectName("rf_fenleijieguo")
        self.rf_fenleijieguo.setColumnCount(0)
        self.rf_fenleijieguo.setRowCount(0)
        self.gridLayout_5.addWidget(self.rf_fenleijieguo, 3, 1, 1, 1)
        self.rf_clfReport = QtWidgets.QTextBrowser(self.page_RF)
        self.rf_clfReport.setObjectName("rf_clfReport")
        self.gridLayout_5.addWidget(self.rf_clfReport, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_RF)
        self.page_ANN = QtWidgets.QWidget()
        self.page_ANN.setObjectName("page_ANN")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_ANN)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_hidden_ann = QtWidgets.QLabel(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_hidden_ann.setFont(font)
        self.label_hidden_ann.setObjectName("label_hidden_ann")
        self.horizontalLayout_9.addWidget(self.label_hidden_ann)
        self.hidden_ann = QtWidgets.QLineEdit(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.hidden_ann.setFont(font)
        self.hidden_ann.setObjectName("hidden_ann")
        self.horizontalLayout_9.addWidget(self.hidden_ann)
        self.label_active_ann = QtWidgets.QLabel(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_active_ann.setFont(font)
        self.label_active_ann.setObjectName("label_active_ann")
        self.horizontalLayout_9.addWidget(self.label_active_ann)
        self.comboBox_active_ann = QtWidgets.QComboBox(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_active_ann.setFont(font)
        self.comboBox_active_ann.setObjectName("comboBox_active_ann")
        self.comboBox_active_ann.addItem("")
        self.comboBox_active_ann.addItem("")
        self.comboBox_active_ann.addItem("")
        self.comboBox_active_ann.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_active_ann)
        self.label_solver_ann = QtWidgets.QLabel(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_solver_ann.setFont(font)
        self.label_solver_ann.setObjectName("label_solver_ann")
        self.horizontalLayout_9.addWidget(self.label_solver_ann)
        self.comboBox_solver_ann = QtWidgets.QComboBox(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_solver_ann.setFont(font)
        self.comboBox_solver_ann.setObjectName("comboBox_solver_ann")
        self.comboBox_solver_ann.addItem("")
        self.comboBox_solver_ann.addItem("")
        self.comboBox_solver_ann.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox_solver_ann)
        self.label_alpha_ann = QtWidgets.QLabel(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_alpha_ann.setFont(font)
        self.label_alpha_ann.setObjectName("label_alpha_ann")
        self.horizontalLayout_9.addWidget(self.label_alpha_ann)
        self.alpha_ann = QtWidgets.QLineEdit(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.alpha_ann.setFont(font)
        self.alpha_ann.setObjectName("alpha_ann")
        self.horizontalLayout_9.addWidget(self.alpha_ann)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 0, 0, 1, 2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.xunlian_ann = QtWidgets.QPushButton(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_ann.setFont(font)
        self.xunlian_ann.setObjectName("xunlian_ann")
        self.horizontalLayout_10.addWidget(self.xunlian_ann)
        self.baocunmoxing_ann = QtWidgets.QPushButton(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_ann.setFont(font)
        self.baocunmoxing_ann.setObjectName("baocunmoxing_ann")
        self.horizontalLayout_10.addWidget(self.baocunmoxing_ann)
        self.daorumoxing_ann = QtWidgets.QPushButton(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_ann.setFont(font)
        self.daorumoxing_ann.setObjectName("daorumoxing_ann")
        self.horizontalLayout_10.addWidget(self.daorumoxing_ann)
        self.ceshijieguo_ann = QtWidgets.QPushButton(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshijieguo_ann.setFont(font)
        self.ceshijieguo_ann.setObjectName("ceshijieguo_ann")
        self.horizontalLayout_10.addWidget(self.ceshijieguo_ann)
        self.baocunshuju_ann = QtWidgets.QPushButton(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_ann.setFont(font)
        self.baocunshuju_ann.setObjectName("baocunshuju_ann")
        self.horizontalLayout_10.addWidget(self.baocunshuju_ann)
        self.gridLayout_6.addLayout(self.horizontalLayout_10, 1, 0, 1, 2)
        self.label_fenleijieguo_ann = QtWidgets.QLabel(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_fenleijieguo_ann.setFont(font)
        self.label_fenleijieguo_ann.setObjectName("label_fenleijieguo_ann")
        self.gridLayout_6.addWidget(self.label_fenleijieguo_ann, 2, 1, 1, 1)
        self.ann_fenleijieguo = QtWidgets.QTableWidget(self.page_ANN)
        self.ann_fenleijieguo.setObjectName("ann_fenleijieguo")
        self.ann_fenleijieguo.setColumnCount(0)
        self.ann_fenleijieguo.setRowCount(0)
        self.gridLayout_6.addWidget(self.ann_fenleijieguo, 3, 1, 1, 1)
        self.ann_clfReport = QtWidgets.QTextBrowser(self.page_ANN)
        self.ann_clfReport.setObjectName("ann_clfReport")
        self.gridLayout_6.addWidget(self.ann_clfReport, 3, 0, 1, 1)
        self.label_report_ann = QtWidgets.QLabel(self.page_ANN)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_report_ann.setFont(font)
        self.label_report_ann.setObjectName("label_report_ann")
        self.gridLayout_6.addWidget(self.label_report_ann, 2, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_ANN)
        self.page_NBC = QtWidgets.QWidget()
        self.page_NBC.setObjectName("page_NBC")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_NBC)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_report_nbc = QtWidgets.QLabel(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_report_nbc.setFont(font)
        self.label_report_nbc.setObjectName("label_report_nbc")
        self.gridLayout_7.addWidget(self.label_report_nbc, 2, 0, 1, 1)
        self.nbc_fenleijieguo = QtWidgets.QTableWidget(self.page_NBC)
        self.nbc_fenleijieguo.setObjectName("nbc_fenleijieguo")
        self.nbc_fenleijieguo.setColumnCount(0)
        self.nbc_fenleijieguo.setRowCount(0)
        self.gridLayout_7.addWidget(self.nbc_fenleijieguo, 3, 1, 1, 1)
        self.nbc_clfReport = QtWidgets.QTextBrowser(self.page_NBC)
        self.nbc_clfReport.setObjectName("nbc_clfReport")
        self.gridLayout_7.addWidget(self.nbc_clfReport, 3, 0, 1, 1)
        self.label_fenleijieguo_nbc = QtWidgets.QLabel(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_fenleijieguo_nbc.setFont(font)
        self.label_fenleijieguo_nbc.setObjectName("label_fenleijieguo_nbc")
        self.gridLayout_7.addWidget(self.label_fenleijieguo_nbc, 2, 1, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_type_nbc = QtWidgets.QLabel(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_type_nbc.setFont(font)
        self.label_type_nbc.setObjectName("label_type_nbc")
        self.horizontalLayout_11.addWidget(self.label_type_nbc)
        self.comboBox_type_nbc = QtWidgets.QComboBox(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.comboBox_type_nbc.setFont(font)
        self.comboBox_type_nbc.setObjectName("comboBox_type_nbc")
        self.comboBox_type_nbc.addItem("")
        self.comboBox_type_nbc.addItem("")
        self.comboBox_type_nbc.addItem("")
        self.comboBox_type_nbc.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_type_nbc)
        self.label_alpha_nbc = QtWidgets.QLabel(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_alpha_nbc.setFont(font)
        self.label_alpha_nbc.setObjectName("label_alpha_nbc")
        self.horizontalLayout_11.addWidget(self.label_alpha_nbc)
        self.alpha_nbc = QtWidgets.QLineEdit(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.alpha_nbc.setFont(font)
        self.alpha_nbc.setObjectName("alpha_nbc")
        self.horizontalLayout_11.addWidget(self.alpha_nbc)
        self.label_binarize_nbc = QtWidgets.QLabel(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_binarize_nbc.setFont(font)
        self.label_binarize_nbc.setObjectName("label_binarize_nbc")
        self.horizontalLayout_11.addWidget(self.label_binarize_nbc)
        self.binarize_nbc = QtWidgets.QLineEdit(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.binarize_nbc.setFont(font)
        self.binarize_nbc.setObjectName("binarize_nbc")
        self.horizontalLayout_11.addWidget(self.binarize_nbc)
        self.Pre_Processing_nbc = QtWidgets.QRadioButton(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_nbc.setFont(font)
        self.Pre_Processing_nbc.setChecked(True)
        self.Pre_Processing_nbc.setObjectName("Pre_Processing_nbc")
        self.horizontalLayout_11.addWidget(self.Pre_Processing_nbc)
        self.gridLayout_7.addLayout(self.horizontalLayout_11, 0, 0, 1, 2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.xunlian_nbc = QtWidgets.QPushButton(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_nbc.setFont(font)
        self.xunlian_nbc.setObjectName("xunlian_nbc")
        self.horizontalLayout_12.addWidget(self.xunlian_nbc)
        self.baocunmoxing_nbc = QtWidgets.QPushButton(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_nbc.setFont(font)
        self.baocunmoxing_nbc.setObjectName("baocunmoxing_nbc")
        self.horizontalLayout_12.addWidget(self.baocunmoxing_nbc)
        self.daorumoxing_nbc = QtWidgets.QPushButton(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_nbc.setFont(font)
        self.daorumoxing_nbc.setObjectName("daorumoxing_nbc")
        self.horizontalLayout_12.addWidget(self.daorumoxing_nbc)
        self.ceshijieguo_nbc = QtWidgets.QPushButton(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshijieguo_nbc.setFont(font)
        self.ceshijieguo_nbc.setObjectName("ceshijieguo_nbc")
        self.horizontalLayout_12.addWidget(self.ceshijieguo_nbc)
        self.baocunshuju_nbc = QtWidgets.QPushButton(self.page_NBC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_nbc.setFont(font)
        self.baocunshuju_nbc.setObjectName("baocunshuju_nbc")
        self.horizontalLayout_12.addWidget(self.baocunshuju_nbc)
        self.gridLayout_7.addLayout(self.horizontalLayout_12, 1, 0, 1, 2)
        self.stackedWidget.addWidget(self.page_NBC)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 6)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1297, 30))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.traindata = QtWidgets.QAction(MainWindow)
        self.traindata.setObjectName("traindata")
        self.testdata = QtWidgets.QAction(MainWindow)
        self.testdata.setObjectName("testdata")
        self.menu.addAction(self.traindata)
        self.menu.addAction(self.testdata)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_nbc.setText(_translate("MainWindow", "NBC"))
        self.label_ceshishuju.setText(_translate("MainWindow", "测试数据"))
        self.button_ann.setText(_translate("MainWindow", "ANN"))
        self.label_xunlianshuju.setText(_translate("MainWindow", "训练数据"))
        self.button_dt.setText(_translate("MainWindow", "DT"))
        self.button_rf.setText(_translate("MainWindow", "RF"))
        self.button_svm.setText(_translate("MainWindow", "SVM"))
        self.button_lda.setText(_translate("MainWindow", "LDA"))
        self.label_solver_lda.setText(_translate("MainWindow", "solver"))
        self.comboBox_solver_lda.setItemText(0, _translate("MainWindow", "svd"))
        self.comboBox_solver_lda.setItemText(1, _translate("MainWindow", "lsqr"))
        self.comboBox_solver_lda.setItemText(2, _translate("MainWindow", "eigen"))
        self.Pre_Processing_lda.setText(_translate("MainWindow", "Pre-Processing"))
        self.label_report_lda.setText(_translate("MainWindow", "LDA分类报告"))
        self.label_fenleijieguo_lda.setText(_translate("MainWindow", "LDA分类结果"))
        self.xunlian_lda.setText(_translate("MainWindow", "训练模型"))
        self.baocunmoxing_lda.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_lda.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_lda.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_lda.setText(_translate("MainWindow", "保存数据"))
        self.label_c_svm.setText(_translate("MainWindow", "惩罚参数C"))
        self.c_svm.setText(_translate("MainWindow", "1.0"))
        self.c_svm.setPlaceholderText(_translate("MainWindow", "请输入正数"))
        self.label_kernel_svm.setText(_translate("MainWindow", "kernel"))
        self.comboBox_kernel_svm.setItemText(0, _translate("MainWindow", "rbf"))
        self.comboBox_kernel_svm.setItemText(1, _translate("MainWindow", "linear"))
        self.comboBox_kernel_svm.setItemText(2, _translate("MainWindow", "poly"))
        self.comboBox_kernel_svm.setItemText(3, _translate("MainWindow", "sigmoid"))
        self.balanced_svm.setText(_translate("MainWindow", "balanced"))
        self.label_decision_svm.setText(_translate("MainWindow", "分类策略"))
        self.comboBox_decision_svm.setItemText(0, _translate("MainWindow", "ovr"))
        self.comboBox_decision_svm.setItemText(1, _translate("MainWindow", "ovo"))
        self.Pre_Processing_svm.setText(_translate("MainWindow", "Pre-Processing"))
        self.label_report_svm.setText(_translate("MainWindow", "SVM分类报告"))
        self.xunlian_svm.setText(_translate("MainWindow", "训练模型"))
        self.baocunmoxing_svm.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_svm.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_svm.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_svm.setText(_translate("MainWindow", "保存数据"))
        self.label_fenleijieguo_svm.setText(_translate("MainWindow", "SVM分类结果"))
        self.checkBox_maxdep_dt.setText(_translate("MainWindow", "深度"))
        self.maxdep_dt.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_minspl_dt.setText(_translate("MainWindow", "min_samples_split"))
        self.minspl_dt.setText(_translate("MainWindow", "2"))
        self.minspl_dt.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_minlea_dt.setText(_translate("MainWindow", "min_samples_leaf"))
        self.minlea_dt.setText(_translate("MainWindow", "1"))
        self.minlea_dt.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.checkBox_balanced_dt.setText(_translate("MainWindow", "balanced"))
        self.xunlian_dt.setText(_translate("MainWindow", "训练模型"))
        self.baocunmoxing_dt.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_dt.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_dt.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_dt.setText(_translate("MainWindow", "保存数据"))
        self.label_report_dt.setText(_translate("MainWindow", "DT分类报告"))
        self.label_fenleijieguo_dt.setText(_translate("MainWindow", "DT分类结果"))
        self.label_numtree_rf.setText(_translate("MainWindow", "子树数量"))
        self.numtree_rf.setText(_translate("MainWindow", "100"))
        self.numtree_rf.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.checkBox_numfea_rf.setText(_translate("MainWindow", "自定义特征数量"))
        self.numfea_rf.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_weight_rf.setText(_translate("MainWindow", "类权重"))
        self.comboBox_weight_rf.setItemText(0, _translate("MainWindow", "None"))
        self.comboBox_weight_rf.setItemText(1, _translate("MainWindow", "balanced"))
        self.comboBox_weight_rf.setItemText(2, _translate("MainWindow", "balanced_subsample"))
        self.xunlian_rf.setText(_translate("MainWindow", "训练模型"))
        self.baocunmoxing_rf.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_rf.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_rf.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_rf.setText(_translate("MainWindow", "保存数据"))
        self.label_report_rf.setText(_translate("MainWindow", "RF分类报告"))
        self.label_fenleijieguo_rf.setText(_translate("MainWindow", "RF分类结果"))
        self.label_hidden_ann.setText(_translate("MainWindow", "隐层大小"))
        self.hidden_ann.setText(_translate("MainWindow", "100"))
        self.hidden_ann.setPlaceholderText(_translate("MainWindow", "请用逗号或分号进行分隔"))
        self.label_active_ann.setText(_translate("MainWindow", "激活函数"))
        self.comboBox_active_ann.setItemText(0, _translate("MainWindow", "relu"))
        self.comboBox_active_ann.setItemText(1, _translate("MainWindow", "identity"))
        self.comboBox_active_ann.setItemText(2, _translate("MainWindow", "logistic"))
        self.comboBox_active_ann.setItemText(3, _translate("MainWindow", "tanh"))
        self.label_solver_ann.setText(_translate("MainWindow", "solver"))
        self.comboBox_solver_ann.setItemText(0, _translate("MainWindow", "adam"))
        self.comboBox_solver_ann.setItemText(1, _translate("MainWindow", "lbfgs"))
        self.comboBox_solver_ann.setItemText(2, _translate("MainWindow", "sgd"))
        self.label_alpha_ann.setText(_translate("MainWindow", "L2惩罚参数"))
        self.alpha_ann.setText(_translate("MainWindow", "0.0001"))
        self.alpha_ann.setPlaceholderText(_translate("MainWindow", "请输入非负数"))
        self.xunlian_ann.setText(_translate("MainWindow", "训练模型"))
        self.baocunmoxing_ann.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_ann.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_ann.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_ann.setText(_translate("MainWindow", "保存数据"))
        self.label_fenleijieguo_ann.setText(_translate("MainWindow", "ANN分类结果"))
        self.label_report_ann.setText(_translate("MainWindow", "ANN分类报告"))
        self.label_report_nbc.setText(_translate("MainWindow", "NBC分类报告"))
        self.label_fenleijieguo_nbc.setText(_translate("MainWindow", "NBC分类结果"))
        self.label_type_nbc.setText(_translate("MainWindow", "朴素贝叶斯类型"))
        self.comboBox_type_nbc.setItemText(0, _translate("MainWindow", "GaussianNB"))
        self.comboBox_type_nbc.setItemText(1, _translate("MainWindow", "MultinomialNB"))
        self.comboBox_type_nbc.setItemText(2, _translate("MainWindow", "ComplementNB"))
        self.comboBox_type_nbc.setItemText(3, _translate("MainWindow", "BernoulliNB"))
        self.label_alpha_nbc.setText(_translate("MainWindow", "平滑参数"))
        self.alpha_nbc.setText(_translate("MainWindow", "1.0"))
        self.alpha_nbc.setPlaceholderText(_translate("MainWindow", "请输入非负数"))
        self.label_binarize_nbc.setText(_translate("MainWindow", "二值化阈值"))
        self.binarize_nbc.setText(_translate("MainWindow", "0.0"))
        self.binarize_nbc.setPlaceholderText(_translate("MainWindow", "请输入样本特征二值化的阈值"))
        self.Pre_Processing_nbc.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_nbc.setText(_translate("MainWindow", "训练模型"))
        self.baocunmoxing_nbc.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_nbc.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_nbc.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_nbc.setText(_translate("MainWindow", "保存数据"))
        self.menu.setTitle(_translate("MainWindow", "数据"))
        self.traindata.setText(_translate("MainWindow", "Train_DATA"))
        self.testdata.setText(_translate("MainWindow", "Test_DATA"))

