# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1170, 791)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_pca = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_pca.setFont(font)
        self.button_pca.setObjectName("button_pca")
        self.gridLayout_2.addWidget(self.button_pca, 3, 0, 1, 1)
        self.label_xunlianshuju = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_xunlianshuju.sizePolicy().hasHeightForWidth())
        self.label_xunlianshuju.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_xunlianshuju.setFont(font)
        self.label_xunlianshuju.setObjectName("label_xunlianshuju")
        self.gridLayout_2.addWidget(self.label_xunlianshuju, 0, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.button_ae = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_ae.setFont(font)
        self.button_ae.setObjectName("button_ae")
        self.gridLayout_2.addWidget(self.button_ae, 3, 4, 1, 1)
        self.button_lae = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_lae.setFont(font)
        self.button_lae.setObjectName("button_lae")
        self.gridLayout_2.addWidget(self.button_lae, 3, 7, 1, 1)
        self.trainWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.trainWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.trainWidget.setMaximumSize(QtCore.QSize(16777215, 230))
        self.trainWidget.setObjectName("trainWidget")
        self.trainWidget.setColumnCount(0)
        self.trainWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.trainWidget, 1, 0, 1, 4)
        self.button_kpca = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_kpca.setFont(font)
        self.button_kpca.setObjectName("button_kpca")
        self.gridLayout_2.addWidget(self.button_kpca, 3, 2, 1, 1)
        self.button_kpls = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_kpls.setFont(font)
        self.button_kpls.setObjectName("button_kpls")
        self.gridLayout_2.addWidget(self.button_kpls, 3, 3, 1, 1)
        self.button_pls = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_pls.setFont(font)
        self.button_pls.setObjectName("button_pls")
        self.gridLayout_2.addWidget(self.button_pls, 3, 1, 1, 1)
        self.button_sae = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_sae.setFont(font)
        self.button_sae.setObjectName("button_sae")
        self.gridLayout_2.addWidget(self.button_sae, 3, 5, 1, 1)
        self.button_dae = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.button_dae.setFont(font)
        self.button_dae.setObjectName("button_dae")
        self.gridLayout_2.addWidget(self.button_dae, 3, 6, 1, 1)
        self.testWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.testWidget.setMinimumSize(QtCore.QSize(0, 200))
        self.testWidget.setMaximumSize(QtCore.QSize(16777215, 230))
        self.testWidget.setObjectName("testWidget")
        self.testWidget.setColumnCount(0)
        self.testWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.testWidget, 1, 4, 1, 4)
        self.label_ceshishuju = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_ceshishuju.setFont(font)
        self.label_ceshishuju.setObjectName("label_ceshishuju")
        self.gridLayout_2.addWidget(self.label_ceshishuju, 0, 6, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_PCA = QtWidgets.QWidget()
        self.page_PCA.setObjectName("page_PCA")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page_PCA)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_n_components_pca = QtWidgets.QLabel(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_n_components_pca.setFont(font)
        self.label_n_components_pca.setObjectName("label_n_components_pca")
        self.horizontalLayout_15.addWidget(self.label_n_components_pca)
        self.n_components_pca = QtWidgets.QLineEdit(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.n_components_pca.setFont(font)
        self.n_components_pca.setObjectName("n_components_pca")
        self.horizontalLayout_15.addWidget(self.n_components_pca)
        self.Pre_Processing_pca = QtWidgets.QRadioButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_pca.setFont(font)
        self.Pre_Processing_pca.setChecked(True)
        self.Pre_Processing_pca.setObjectName("Pre_Processing_pca")
        self.horizontalLayout_15.addWidget(self.Pre_Processing_pca)
        self.gridLayout_8.addLayout(self.horizontalLayout_15, 0, 0, 1, 2)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.xunlian_pca = QtWidgets.QPushButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_pca.setFont(font)
        self.xunlian_pca.setObjectName("xunlian_pca")
        self.horizontalLayout_16.addWidget(self.xunlian_pca)
        self.xunliantezheng_pca = QtWidgets.QPushButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_pca.setFont(font)
        self.xunliantezheng_pca.setObjectName("xunliantezheng_pca")
        self.horizontalLayout_16.addWidget(self.xunliantezheng_pca)
        self.baocunmoxing_pca = QtWidgets.QPushButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_pca.setFont(font)
        self.baocunmoxing_pca.setObjectName("baocunmoxing_pca")
        self.horizontalLayout_16.addWidget(self.baocunmoxing_pca)
        self.daorumoxing_pca = QtWidgets.QPushButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_pca.setFont(font)
        self.daorumoxing_pca.setObjectName("daorumoxing_pca")
        self.horizontalLayout_16.addWidget(self.daorumoxing_pca)
        self.ceshitezheng_pca = QtWidgets.QPushButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_pca.setFont(font)
        self.ceshitezheng_pca.setObjectName("ceshitezheng_pca")
        self.horizontalLayout_16.addWidget(self.ceshitezheng_pca)
        self.baocunshujv_pca = QtWidgets.QPushButton(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshujv_pca.setFont(font)
        self.baocunshujv_pca.setObjectName("baocunshujv_pca")
        self.horizontalLayout_16.addWidget(self.baocunshujv_pca)
        self.gridLayout_8.addLayout(self.horizontalLayout_16, 1, 0, 1, 2)
        self.label_tezhenggongxiantu_pca = QtWidgets.QLabel(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhenggongxiantu_pca.setFont(font)
        self.label_tezhenggongxiantu_pca.setObjectName("label_tezhenggongxiantu_pca")
        self.gridLayout_8.addWidget(self.label_tezhenggongxiantu_pca, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_tezhengshujv_pca = QtWidgets.QLabel(self.page_PCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshujv_pca.setFont(font)
        self.label_tezhengshujv_pca.setObjectName("label_tezhengshujv_pca")
        self.gridLayout_8.addWidget(self.label_tezhengshujv_pca, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pca_features = QtWidgets.QTableWidget(self.page_PCA)
        self.pca_features.setObjectName("pca_features")
        self.pca_features.setColumnCount(0)
        self.pca_features.setRowCount(0)
        self.gridLayout_8.addWidget(self.pca_features, 3, 1, 1, 1)
        self.pca_gongxiantu = QtWidgets.QGraphicsView(self.page_PCA)
        self.pca_gongxiantu.setObjectName("pca_gongxiantu")
        self.gridLayout_8.addWidget(self.pca_gongxiantu, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_PCA)
        self.page_PLS = QtWidgets.QWidget()
        self.page_PLS.setObjectName("page_PLS")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_PLS)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_n_components_pls = QtWidgets.QLabel(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_n_components_pls.setFont(font)
        self.label_n_components_pls.setObjectName("label_n_components_pls")
        self.horizontalLayout_11.addWidget(self.label_n_components_pls)
        self.n_components_pls = QtWidgets.QLineEdit(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.n_components_pls.setFont(font)
        self.n_components_pls.setObjectName("n_components_pls")
        self.horizontalLayout_11.addWidget(self.n_components_pls)
        self.label_biaoqianlieshu_pls = QtWidgets.QLabel(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_biaoqianlieshu_pls.setFont(font)
        self.label_biaoqianlieshu_pls.setObjectName("label_biaoqianlieshu_pls")
        self.horizontalLayout_11.addWidget(self.label_biaoqianlieshu_pls)
        self.biaoqianlieshu_pls = QtWidgets.QLineEdit(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.biaoqianlieshu_pls.setFont(font)
        self.biaoqianlieshu_pls.setObjectName("biaoqianlieshu_pls")
        self.horizontalLayout_11.addWidget(self.biaoqianlieshu_pls)
        self.Pre_Processing_pls = QtWidgets.QRadioButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_pls.setFont(font)
        self.Pre_Processing_pls.setChecked(True)
        self.Pre_Processing_pls.setObjectName("Pre_Processing_pls")
        self.horizontalLayout_11.addWidget(self.Pre_Processing_pls)
        self.gridLayout_9.addLayout(self.horizontalLayout_11, 0, 0, 1, 2)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.xunlian_pls = QtWidgets.QPushButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_pls.setFont(font)
        self.xunlian_pls.setObjectName("xunlian_pls")
        self.horizontalLayout_12.addWidget(self.xunlian_pls)
        self.xunliantezheng_pls = QtWidgets.QPushButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_pls.setFont(font)
        self.xunliantezheng_pls.setObjectName("xunliantezheng_pls")
        self.horizontalLayout_12.addWidget(self.xunliantezheng_pls)
        self.baocunmoxing_pls = QtWidgets.QPushButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_pls.setFont(font)
        self.baocunmoxing_pls.setObjectName("baocunmoxing_pls")
        self.horizontalLayout_12.addWidget(self.baocunmoxing_pls)
        self.daorumoxing_pls = QtWidgets.QPushButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_pls.setFont(font)
        self.daorumoxing_pls.setObjectName("daorumoxing_pls")
        self.horizontalLayout_12.addWidget(self.daorumoxing_pls)
        self.ceshitezheng_pls = QtWidgets.QPushButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_pls.setFont(font)
        self.ceshitezheng_pls.setObjectName("ceshitezheng_pls")
        self.horizontalLayout_12.addWidget(self.ceshitezheng_pls)
        self.baocunshujv_pls = QtWidgets.QPushButton(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshujv_pls.setFont(font)
        self.baocunshujv_pls.setObjectName("baocunshujv_pls")
        self.horizontalLayout_12.addWidget(self.baocunshujv_pls)
        self.gridLayout_9.addLayout(self.horizontalLayout_12, 1, 0, 1, 2)
        self.tezhenggongxiantu_pls = QtWidgets.QLabel(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tezhenggongxiantu_pls.setFont(font)
        self.tezhenggongxiantu_pls.setObjectName("tezhenggongxiantu_pls")
        self.gridLayout_9.addWidget(self.tezhenggongxiantu_pls, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.tezhengshujv_pls = QtWidgets.QLabel(self.page_PLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.tezhengshujv_pls.setFont(font)
        self.tezhengshujv_pls.setObjectName("tezhengshujv_pls")
        self.gridLayout_9.addWidget(self.tezhengshujv_pls, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.pls_features = QtWidgets.QTableWidget(self.page_PLS)
        self.pls_features.setObjectName("pls_features")
        self.pls_features.setColumnCount(0)
        self.pls_features.setRowCount(0)
        self.gridLayout_9.addWidget(self.pls_features, 3, 1, 1, 1)
        self.pls_gongxiantu = QtWidgets.QGraphicsView(self.page_PLS)
        self.pls_gongxiantu.setObjectName("pls_gongxiantu")
        self.gridLayout_9.addWidget(self.pls_gongxiantu, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_PLS)
        self.page_KPCA = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.page_KPCA.sizePolicy().hasHeightForWidth())
        self.page_KPCA.setSizePolicy(sizePolicy)
        self.page_KPCA.setObjectName("page_KPCA")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.page_KPCA)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_tezhenggonxiantu_kpca = QtWidgets.QLabel(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhenggonxiantu_kpca.setFont(font)
        self.label_tezhenggonxiantu_kpca.setObjectName("label_tezhenggonxiantu_kpca")
        self.gridLayout_6.addWidget(self.label_tezhenggonxiantu_kpca, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.kpca_features = QtWidgets.QTableWidget(self.page_KPCA)
        self.kpca_features.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.kpca_features.setObjectName("kpca_features")
        self.kpca_features.setColumnCount(0)
        self.kpca_features.setRowCount(0)
        self.gridLayout_6.addWidget(self.kpca_features, 3, 1, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_n_components_kpca = QtWidgets.QLabel(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_n_components_kpca.setFont(font)
        self.label_n_components_kpca.setObjectName("label_n_components_kpca")
        self.horizontalLayout_9.addWidget(self.label_n_components_kpca)
        self.n_components_kpca = QtWidgets.QLineEdit(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.n_components_kpca.setFont(font)
        self.n_components_kpca.setText("")
        self.n_components_kpca.setObjectName("n_components_kpca")
        self.horizontalLayout_9.addWidget(self.n_components_kpca)
        self.label_kernel_function_kpca = QtWidgets.QLabel(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_kernel_function_kpca.setFont(font)
        self.label_kernel_function_kpca.setObjectName("label_kernel_function_kpca")
        self.horizontalLayout_9.addWidget(self.label_kernel_function_kpca)
        self.kernel_function_kpca = QtWidgets.QComboBox(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.kernel_function_kpca.setFont(font)
        self.kernel_function_kpca.setObjectName("kernel_function_kpca")
        self.kernel_function_kpca.addItem("")
        self.kernel_function_kpca.addItem("")
        self.kernel_function_kpca.addItem("")
        self.kernel_function_kpca.addItem("")
        self.kernel_function_kpca.addItem("")
        self.horizontalLayout_9.addWidget(self.kernel_function_kpca)
        self.label_nkernel_components_kpca = QtWidgets.QLabel(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_nkernel_components_kpca.setFont(font)
        self.label_nkernel_components_kpca.setObjectName("label_nkernel_components_kpca")
        self.horizontalLayout_9.addWidget(self.label_nkernel_components_kpca)
        self.nkernel_components_kpca = QtWidgets.QLineEdit(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.nkernel_components_kpca.setFont(font)
        self.nkernel_components_kpca.setText("")
        self.nkernel_components_kpca.setObjectName("nkernel_components_kpca")
        self.horizontalLayout_9.addWidget(self.nkernel_components_kpca)
        self.Pre_Processing_kpca = QtWidgets.QRadioButton(self.page_KPCA)
        self.Pre_Processing_kpca.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_kpca.setFont(font)
        self.Pre_Processing_kpca.setChecked(True)
        self.Pre_Processing_kpca.setObjectName("Pre_Processing_kpca")
        self.horizontalLayout_9.addWidget(self.Pre_Processing_kpca)
        self.gridLayout_6.addLayout(self.horizontalLayout_9, 0, 0, 1, 2)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.xunlian_kpca = QtWidgets.QPushButton(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_kpca.setFont(font)
        self.xunlian_kpca.setObjectName("xunlian_kpca")
        self.horizontalLayout_8.addWidget(self.xunlian_kpca)
        self.xunliantezheng_kpca = QtWidgets.QPushButton(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_kpca.setFont(font)
        self.xunliantezheng_kpca.setObjectName("xunliantezheng_kpca")
        self.horizontalLayout_8.addWidget(self.xunliantezheng_kpca)
        self.baocunmoxing_kpca = QtWidgets.QPushButton(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_kpca.setFont(font)
        self.baocunmoxing_kpca.setObjectName("baocunmoxing_kpca")
        self.horizontalLayout_8.addWidget(self.baocunmoxing_kpca)
        self.daorumoxing_kpca = QtWidgets.QPushButton(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_kpca.setFont(font)
        self.daorumoxing_kpca.setObjectName("daorumoxing_kpca")
        self.horizontalLayout_8.addWidget(self.daorumoxing_kpca)
        self.ceshitezheng_kpca = QtWidgets.QPushButton(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_kpca.setFont(font)
        self.ceshitezheng_kpca.setObjectName("ceshitezheng_kpca")
        self.horizontalLayout_8.addWidget(self.ceshitezheng_kpca)
        self.baocunshujv_kpca = QtWidgets.QPushButton(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshujv_kpca.setFont(font)
        self.baocunshujv_kpca.setObjectName("baocunshujv_kpca")
        self.horizontalLayout_8.addWidget(self.baocunshujv_kpca)
        self.gridLayout_6.addLayout(self.horizontalLayout_8, 1, 0, 1, 2)
        self.label_tezhengshujv_kpca = QtWidgets.QLabel(self.page_KPCA)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshujv_kpca.setFont(font)
        self.label_tezhengshujv_kpca.setObjectName("label_tezhengshujv_kpca")
        self.gridLayout_6.addWidget(self.label_tezhengshujv_kpca, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.kpca_gongxiantu = QtWidgets.QGraphicsView(self.page_KPCA)
        self.kpca_gongxiantu.setObjectName("kpca_gongxiantu")
        self.gridLayout_6.addWidget(self.kpca_gongxiantu, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_KPCA)
        self.page_KPLS = QtWidgets.QWidget()
        self.page_KPLS.setObjectName("page_KPLS")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.page_KPLS)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_n_components_kpls = QtWidgets.QLabel(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_n_components_kpls.setFont(font)
        self.label_n_components_kpls.setObjectName("label_n_components_kpls")
        self.horizontalLayout_13.addWidget(self.label_n_components_kpls)
        self.n_components_kpls = QtWidgets.QLineEdit(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.n_components_kpls.setFont(font)
        self.n_components_kpls.setObjectName("n_components_kpls")
        self.horizontalLayout_13.addWidget(self.n_components_kpls)
        self.label_biaoqianlieshu_kpls = QtWidgets.QLabel(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_biaoqianlieshu_kpls.setFont(font)
        self.label_biaoqianlieshu_kpls.setObjectName("label_biaoqianlieshu_kpls")
        self.horizontalLayout_13.addWidget(self.label_biaoqianlieshu_kpls)
        self.biaoqianlieshu_kpls = QtWidgets.QLineEdit(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.biaoqianlieshu_kpls.setFont(font)
        self.biaoqianlieshu_kpls.setObjectName("biaoqianlieshu_kpls")
        self.horizontalLayout_13.addWidget(self.biaoqianlieshu_kpls)
        self.label_kernel_function_kpls = QtWidgets.QLabel(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_kernel_function_kpls.setFont(font)
        self.label_kernel_function_kpls.setObjectName("label_kernel_function_kpls")
        self.horizontalLayout_13.addWidget(self.label_kernel_function_kpls)
        self.kernel_function_kpls = QtWidgets.QComboBox(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.kernel_function_kpls.setFont(font)
        self.kernel_function_kpls.setObjectName("kernel_function_kpls")
        self.kernel_function_kpls.addItem("")
        self.kernel_function_kpls.addItem("")
        self.kernel_function_kpls.addItem("")
        self.kernel_function_kpls.addItem("")
        self.kernel_function_kpls.addItem("")
        self.horizontalLayout_13.addWidget(self.kernel_function_kpls)
        self.label_nkernel_components_kpls = QtWidgets.QLabel(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_nkernel_components_kpls.setFont(font)
        self.label_nkernel_components_kpls.setObjectName("label_nkernel_components_kpls")
        self.horizontalLayout_13.addWidget(self.label_nkernel_components_kpls)
        self.nkernel_components_kpls = QtWidgets.QLineEdit(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.nkernel_components_kpls.setFont(font)
        self.nkernel_components_kpls.setObjectName("nkernel_components_kpls")
        self.horizontalLayout_13.addWidget(self.nkernel_components_kpls)
        self.Pre_Processing_kpls = QtWidgets.QRadioButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.Pre_Processing_kpls.setFont(font)
        self.Pre_Processing_kpls.setChecked(True)
        self.Pre_Processing_kpls.setObjectName("Pre_Processing_kpls")
        self.horizontalLayout_13.addWidget(self.Pre_Processing_kpls)
        self.gridLayout_7.addLayout(self.horizontalLayout_13, 0, 0, 1, 2)
        self.label_tezhengshujv_pls = QtWidgets.QLabel(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshujv_pls.setFont(font)
        self.label_tezhengshujv_pls.setObjectName("label_tezhengshujv_pls")
        self.gridLayout_7.addWidget(self.label_tezhengshujv_pls, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_tezhenggonxiantu_kpls = QtWidgets.QLabel(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhenggonxiantu_kpls.setFont(font)
        self.label_tezhenggonxiantu_kpls.setObjectName("label_tezhenggonxiantu_kpls")
        self.gridLayout_7.addWidget(self.label_tezhenggonxiantu_kpls, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.xunlian_kpls = QtWidgets.QPushButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_kpls.setFont(font)
        self.xunlian_kpls.setObjectName("xunlian_kpls")
        self.horizontalLayout_14.addWidget(self.xunlian_kpls)
        self.xunliantezheng_kpls = QtWidgets.QPushButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_kpls.setFont(font)
        self.xunliantezheng_kpls.setObjectName("xunliantezheng_kpls")
        self.horizontalLayout_14.addWidget(self.xunliantezheng_kpls)
        self.baocunmoxing_kpls = QtWidgets.QPushButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxing_kpls.setFont(font)
        self.baocunmoxing_kpls.setObjectName("baocunmoxing_kpls")
        self.horizontalLayout_14.addWidget(self.baocunmoxing_kpls)
        self.daorumoxing_kpls = QtWidgets.QPushButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxing_kpls.setFont(font)
        self.daorumoxing_kpls.setObjectName("daorumoxing_kpls")
        self.horizontalLayout_14.addWidget(self.daorumoxing_kpls)
        self.ceshitezheng_kpls = QtWidgets.QPushButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_kpls.setFont(font)
        self.ceshitezheng_kpls.setObjectName("ceshitezheng_kpls")
        self.horizontalLayout_14.addWidget(self.ceshitezheng_kpls)
        self.baocunshujv_kpls = QtWidgets.QPushButton(self.page_KPLS)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshujv_kpls.setFont(font)
        self.baocunshujv_kpls.setObjectName("baocunshujv_kpls")
        self.horizontalLayout_14.addWidget(self.baocunshujv_kpls)
        self.gridLayout_7.addLayout(self.horizontalLayout_14, 1, 0, 1, 2)
        self.kpls_features = QtWidgets.QTableWidget(self.page_KPLS)
        self.kpls_features.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.SizeVerCursor))
        self.kpls_features.setObjectName("kpls_features")
        self.kpls_features.setColumnCount(0)
        self.kpls_features.setRowCount(0)
        self.gridLayout_7.addWidget(self.kpls_features, 3, 1, 1, 1)
        self.kpls_gongxiantu = QtWidgets.QGraphicsView(self.page_KPLS)
        self.kpls_gongxiantu.setObjectName("kpls_gongxiantu")
        self.gridLayout_7.addWidget(self.kpls_gongxiantu, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_KPLS)
        self.page_AE = QtWidgets.QWidget()
        self.page_AE.setObjectName("page_AE")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_AE)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_yincengjiegou_ae = QtWidgets.QLabel(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_yincengjiegou_ae.setFont(font)
        self.label_yincengjiegou_ae.setObjectName("label_yincengjiegou_ae")
        self.horizontalLayout.addWidget(self.label_yincengjiegou_ae)
        self.structure_ae = QtWidgets.QLineEdit(self.page_AE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.structure_ae.setFont(font)
        self.structure_ae.setObjectName("structure_ae")
        self.horizontalLayout.addWidget(self.structure_ae)
        self.label_epoch_ae = QtWidgets.QLabel(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_epoch_ae.setFont(font)
        self.label_epoch_ae.setObjectName("label_epoch_ae")
        self.horizontalLayout.addWidget(self.label_epoch_ae)
        self.epoch_ae = QtWidgets.QLineEdit(self.page_AE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.epoch_ae.setFont(font)
        self.epoch_ae.setObjectName("epoch_ae")
        self.horizontalLayout.addWidget(self.epoch_ae)
        self.label_batchsize_ae = QtWidgets.QLabel(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_batchsize_ae.setFont(font)
        self.label_batchsize_ae.setObjectName("label_batchsize_ae")
        self.horizontalLayout.addWidget(self.label_batchsize_ae)
        self.batchsize_ae = QtWidgets.QLineEdit(self.page_AE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.batchsize_ae.setFont(font)
        self.batchsize_ae.setObjectName("batchsize_ae")
        self.horizontalLayout.addWidget(self.batchsize_ae)
        self.earlystop_ae = QtWidgets.QRadioButton(self.page_AE)
        self.earlystop_ae.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.earlystop_ae.setFont(font)
        self.earlystop_ae.setChecked(True)
        self.earlystop_ae.setObjectName("earlystop_ae")
        self.horizontalLayout.addWidget(self.earlystop_ae)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chushihua_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.chushihua_ae.setFont(font)
        self.chushihua_ae.setObjectName("chushihua_ae")
        self.horizontalLayout_2.addWidget(self.chushihua_ae)
        self.daorumoxin_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxin_ae.setFont(font)
        self.daorumoxin_ae.setObjectName("daorumoxin_ae")
        self.horizontalLayout_2.addWidget(self.daorumoxin_ae)
        self.xunlian_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_ae.setFont(font)
        self.xunlian_ae.setObjectName("xunlian_ae")
        self.horizontalLayout_2.addWidget(self.xunlian_ae)
        self.xunliantezheng_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_ae.setFont(font)
        self.xunliantezheng_ae.setObjectName("xunliantezheng_ae")
        self.horizontalLayout_2.addWidget(self.xunliantezheng_ae)
        self.baocunmoxin_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxin_ae.setFont(font)
        self.baocunmoxin_ae.setObjectName("baocunmoxin_ae")
        self.horizontalLayout_2.addWidget(self.baocunmoxin_ae)
        self.ceshitezheng_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_ae.setFont(font)
        self.ceshitezheng_ae.setObjectName("ceshitezheng_ae")
        self.horizontalLayout_2.addWidget(self.ceshitezheng_ae)
        self.baocunshuju_ae = QtWidgets.QPushButton(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_ae.setFont(font)
        self.baocunshuju_ae.setObjectName("baocunshuju_ae")
        self.horizontalLayout_2.addWidget(self.baocunshuju_ae)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.label_xunlianwucha_ae_ = QtWidgets.QLabel(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_xunlianwucha_ae_.setFont(font)
        self.label_xunlianwucha_ae_.setObjectName("label_xunlianwucha_ae_")
        self.gridLayout_3.addWidget(self.label_xunlianwucha_ae_, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_tezhengshuju_ae = QtWidgets.QLabel(self.page_AE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshuju_ae.setFont(font)
        self.label_tezhengshuju_ae.setObjectName("label_tezhengshuju_ae")
        self.gridLayout_3.addWidget(self.label_tezhengshuju_ae, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.history_ae = QtWidgets.QWidget(self.page_AE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_ae.sizePolicy().hasHeightForWidth())
        self.history_ae.setSizePolicy(sizePolicy)
        self.history_ae.setObjectName("history_ae")
        self.gridLayout_3.addWidget(self.history_ae, 3, 0, 1, 1)
        self.AE_features = QtWidgets.QTableWidget(self.page_AE)
        self.AE_features.setObjectName("AE_features")
        self.AE_features.setColumnCount(0)
        self.AE_features.setRowCount(0)
        self.gridLayout_3.addWidget(self.AE_features, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_AE)
        self.page_SAE = QtWidgets.QWidget()
        self.page_SAE.setObjectName("page_SAE")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_SAE)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_yincengjiegou_sae = QtWidgets.QLabel(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_yincengjiegou_sae.setFont(font)
        self.label_yincengjiegou_sae.setObjectName("label_yincengjiegou_sae")
        self.horizontalLayout_3.addWidget(self.label_yincengjiegou_sae)
        self.structure_sae = QtWidgets.QLineEdit(self.page_SAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.structure_sae.setFont(font)
        self.structure_sae.setObjectName("structure_sae")
        self.horizontalLayout_3.addWidget(self.structure_sae)
        self.label_epoch_sae = QtWidgets.QLabel(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_epoch_sae.setFont(font)
        self.label_epoch_sae.setObjectName("label_epoch_sae")
        self.horizontalLayout_3.addWidget(self.label_epoch_sae)
        self.epoch_sae = QtWidgets.QLineEdit(self.page_SAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.epoch_sae.setFont(font)
        self.epoch_sae.setObjectName("epoch_sae")
        self.horizontalLayout_3.addWidget(self.epoch_sae)
        self.label_batchsize_sae = QtWidgets.QLabel(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_batchsize_sae.setFont(font)
        self.label_batchsize_sae.setObjectName("label_batchsize_sae")
        self.horizontalLayout_3.addWidget(self.label_batchsize_sae)
        self.batchsize_sae = QtWidgets.QLineEdit(self.page_SAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.batchsize_sae.setFont(font)
        self.batchsize_sae.setObjectName("batchsize_sae")
        self.horizontalLayout_3.addWidget(self.batchsize_sae)
        self.earlystop_sae = QtWidgets.QRadioButton(self.page_SAE)
        self.earlystop_sae.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.earlystop_sae.setFont(font)
        self.earlystop_sae.setChecked(True)
        self.earlystop_sae.setObjectName("earlystop_sae")
        self.horizontalLayout_3.addWidget(self.earlystop_sae)
        self.gridLayout_4.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.chushihua_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.chushihua_sae.setFont(font)
        self.chushihua_sae.setObjectName("chushihua_sae")
        self.horizontalLayout_4.addWidget(self.chushihua_sae)
        self.daorumoxin_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxin_sae.setFont(font)
        self.daorumoxin_sae.setObjectName("daorumoxin_sae")
        self.horizontalLayout_4.addWidget(self.daorumoxin_sae)
        self.xunlian_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_sae.setFont(font)
        self.xunlian_sae.setObjectName("xunlian_sae")
        self.horizontalLayout_4.addWidget(self.xunlian_sae)
        self.xunliantezheng_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_sae.setFont(font)
        self.xunliantezheng_sae.setObjectName("xunliantezheng_sae")
        self.horizontalLayout_4.addWidget(self.xunliantezheng_sae)
        self.baocunmoxin_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxin_sae.setFont(font)
        self.baocunmoxin_sae.setObjectName("baocunmoxin_sae")
        self.horizontalLayout_4.addWidget(self.baocunmoxin_sae)
        self.ceshitezheng_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_sae.setFont(font)
        self.ceshitezheng_sae.setObjectName("ceshitezheng_sae")
        self.horizontalLayout_4.addWidget(self.ceshitezheng_sae)
        self.baocunshuju_sae = QtWidgets.QPushButton(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_sae.setFont(font)
        self.baocunshuju_sae.setObjectName("baocunshuju_sae")
        self.horizontalLayout_4.addWidget(self.baocunshuju_sae)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.label_xunlianwucha_sae = QtWidgets.QLabel(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_xunlianwucha_sae.setFont(font)
        self.label_xunlianwucha_sae.setObjectName("label_xunlianwucha_sae")
        self.gridLayout_4.addWidget(self.label_xunlianwucha_sae, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_tezhengshuju_sae = QtWidgets.QLabel(self.page_SAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshuju_sae.setFont(font)
        self.label_tezhengshuju_sae.setObjectName("label_tezhengshuju_sae")
        self.gridLayout_4.addWidget(self.label_tezhengshuju_sae, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.history_sae = QtWidgets.QWidget(self.page_SAE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_sae.sizePolicy().hasHeightForWidth())
        self.history_sae.setSizePolicy(sizePolicy)
        self.history_sae.setObjectName("history_sae")
        self.gridLayout_4.addWidget(self.history_sae, 3, 0, 1, 1)
        self.SAE_features = QtWidgets.QTableWidget(self.page_SAE)
        self.SAE_features.setObjectName("SAE_features")
        self.SAE_features.setColumnCount(0)
        self.SAE_features.setRowCount(0)
        self.gridLayout_4.addWidget(self.SAE_features, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_SAE)
        self.page_DAE = QtWidgets.QWidget()
        self.page_DAE.setObjectName("page_DAE")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_DAE)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_yincengjiegou_dae = QtWidgets.QLabel(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_yincengjiegou_dae.setFont(font)
        self.label_yincengjiegou_dae.setObjectName("label_yincengjiegou_dae")
        self.horizontalLayout_6.addWidget(self.label_yincengjiegou_dae)
        self.structure_dae = QtWidgets.QLineEdit(self.page_DAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.structure_dae.setFont(font)
        self.structure_dae.setObjectName("structure_dae")
        self.horizontalLayout_6.addWidget(self.structure_dae)
        self.label_epoch_dae = QtWidgets.QLabel(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_epoch_dae.setFont(font)
        self.label_epoch_dae.setObjectName("label_epoch_dae")
        self.horizontalLayout_6.addWidget(self.label_epoch_dae)
        self.epoch_dae = QtWidgets.QLineEdit(self.page_DAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.epoch_dae.setFont(font)
        self.epoch_dae.setObjectName("epoch_dae")
        self.horizontalLayout_6.addWidget(self.epoch_dae)
        self.label_batchsize_dae = QtWidgets.QLabel(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_batchsize_dae.setFont(font)
        self.label_batchsize_dae.setObjectName("label_batchsize_dae")
        self.horizontalLayout_6.addWidget(self.label_batchsize_dae)
        self.batchsize_dae = QtWidgets.QLineEdit(self.page_DAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.batchsize_dae.setFont(font)
        self.batchsize_dae.setObjectName("batchsize_dae")
        self.horizontalLayout_6.addWidget(self.batchsize_dae)
        self.label_corrupt_dae = QtWidgets.QLabel(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_corrupt_dae.setFont(font)
        self.label_corrupt_dae.setObjectName("label_corrupt_dae")
        self.horizontalLayout_6.addWidget(self.label_corrupt_dae)
        self.corrupt_dae = QtWidgets.QLineEdit(self.page_DAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.corrupt_dae.setFont(font)
        self.corrupt_dae.setObjectName("corrupt_dae")
        self.horizontalLayout_6.addWidget(self.corrupt_dae)
        self.earlystop_dae = QtWidgets.QRadioButton(self.page_DAE)
        self.earlystop_dae.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.earlystop_dae.setFont(font)
        self.earlystop_dae.setChecked(True)
        self.earlystop_dae.setObjectName("earlystop_dae")
        self.horizontalLayout_6.addWidget(self.earlystop_dae)
        self.gridLayout_5.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chushihua_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.chushihua_dae.setFont(font)
        self.chushihua_dae.setObjectName("chushihua_dae")
        self.horizontalLayout_5.addWidget(self.chushihua_dae)
        self.daorumoxin_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxin_dae.setFont(font)
        self.daorumoxin_dae.setObjectName("daorumoxin_dae")
        self.horizontalLayout_5.addWidget(self.daorumoxin_dae)
        self.xunlian_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_dae.setFont(font)
        self.xunlian_dae.setObjectName("xunlian_dae")
        self.horizontalLayout_5.addWidget(self.xunlian_dae)
        self.xunliantezheng_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_dae.setFont(font)
        self.xunliantezheng_dae.setObjectName("xunliantezheng_dae")
        self.horizontalLayout_5.addWidget(self.xunliantezheng_dae)
        self.baocunmoxin_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxin_dae.setFont(font)
        self.baocunmoxin_dae.setObjectName("baocunmoxin_dae")
        self.horizontalLayout_5.addWidget(self.baocunmoxin_dae)
        self.ceshitezheng_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_dae.setFont(font)
        self.ceshitezheng_dae.setObjectName("ceshitezheng_dae")
        self.horizontalLayout_5.addWidget(self.ceshitezheng_dae)
        self.baocunshuju_dae = QtWidgets.QPushButton(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_dae.setFont(font)
        self.baocunshuju_dae.setObjectName("baocunshuju_dae")
        self.horizontalLayout_5.addWidget(self.baocunshuju_dae)
        self.gridLayout_5.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.label_xunlianwucha_dae = QtWidgets.QLabel(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_xunlianwucha_dae.setFont(font)
        self.label_xunlianwucha_dae.setObjectName("label_xunlianwucha_dae")
        self.gridLayout_5.addWidget(self.label_xunlianwucha_dae, 2, 0, 1, 1, QtCore.Qt.AlignHCenter)
        self.label_tezhengshuju_dae = QtWidgets.QLabel(self.page_DAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshuju_dae.setFont(font)
        self.label_tezhengshuju_dae.setObjectName("label_tezhengshuju_dae")
        self.gridLayout_5.addWidget(self.label_tezhengshuju_dae, 2, 1, 1, 1, QtCore.Qt.AlignHCenter)
        self.history_dae = QtWidgets.QWidget(self.page_DAE)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.history_dae.sizePolicy().hasHeightForWidth())
        self.history_dae.setSizePolicy(sizePolicy)
        self.history_dae.setObjectName("history_dae")
        self.gridLayout_5.addWidget(self.history_dae, 3, 0, 1, 1)
        self.DAE_features = QtWidgets.QTableWidget(self.page_DAE)
        self.DAE_features.setObjectName("DAE_features")
        self.DAE_features.setColumnCount(0)
        self.DAE_features.setRowCount(0)
        self.gridLayout_5.addWidget(self.DAE_features, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_DAE)
        self.page_LAE = QtWidgets.QWidget()
        self.page_LAE.setObjectName("page_LAE")
        self.gridLayout = QtWidgets.QGridLayout(self.page_LAE)
        self.gridLayout.setObjectName("gridLayout")
        self.label_yincengjiegou_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_yincengjiegou_lae.setFont(font)
        self.label_yincengjiegou_lae.setObjectName("label_yincengjiegou_lae")
        self.gridLayout.addWidget(self.label_yincengjiegou_lae, 0, 0, 1, 1)
        self.structure_lae = QtWidgets.QLineEdit(self.page_LAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.structure_lae.setFont(font)
        self.structure_lae.setObjectName("structure_lae")
        self.gridLayout.addWidget(self.structure_lae, 0, 1, 1, 1)
        self.label_epoch_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_epoch_lae.setFont(font)
        self.label_epoch_lae.setObjectName("label_epoch_lae")
        self.gridLayout.addWidget(self.label_epoch_lae, 0, 2, 1, 1)
        self.epoch_lae = QtWidgets.QLineEdit(self.page_LAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.epoch_lae.setFont(font)
        self.epoch_lae.setObjectName("epoch_lae")
        self.gridLayout.addWidget(self.epoch_lae, 0, 3, 1, 1)
        self.label_batchsize_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_batchsize_lae.setFont(font)
        self.label_batchsize_lae.setObjectName("label_batchsize_lae")
        self.gridLayout.addWidget(self.label_batchsize_lae, 0, 4, 1, 1)
        self.batchsize_lae = QtWidgets.QLineEdit(self.page_LAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.batchsize_lae.setFont(font)
        self.batchsize_lae.setObjectName("batchsize_lae")
        self.gridLayout.addWidget(self.batchsize_lae, 0, 5, 1, 1)
        self.label_zuoyong_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_zuoyong_lae.setFont(font)
        self.label_zuoyong_lae.setObjectName("label_zuoyong_lae")
        self.gridLayout.addWidget(self.label_zuoyong_lae, 0, 6, 1, 1)
        self.zuoyong_lae = QtWidgets.QComboBox(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.zuoyong_lae.setFont(font)
        self.zuoyong_lae.setObjectName("zuoyong_lae")
        self.zuoyong_lae.addItem("")
        self.zuoyong_lae.addItem("")
        self.gridLayout.addWidget(self.zuoyong_lae, 0, 7, 1, 1)
        self.label_biaoqianlieshu_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_biaoqianlieshu_lae.setFont(font)
        self.label_biaoqianlieshu_lae.setObjectName("label_biaoqianlieshu_lae")
        self.gridLayout.addWidget(self.label_biaoqianlieshu_lae, 0, 8, 1, 1)
        self.biaoqianlieshu_lae = QtWidgets.QLineEdit(self.page_LAE)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.biaoqianlieshu_lae.setFont(font)
        self.biaoqianlieshu_lae.setObjectName("biaoqianlieshu_lae")
        self.gridLayout.addWidget(self.biaoqianlieshu_lae, 0, 9, 1, 1)
        self.earlystop_lae = QtWidgets.QRadioButton(self.page_LAE)
        self.earlystop_lae.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.earlystop_lae.setFont(font)
        self.earlystop_lae.setChecked(True)
        self.earlystop_lae.setObjectName("earlystop_lae")
        self.gridLayout.addWidget(self.earlystop_lae, 0, 10, 1, 1)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.chushihua_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.chushihua_lae.setFont(font)
        self.chushihua_lae.setObjectName("chushihua_lae")
        self.horizontalLayout_10.addWidget(self.chushihua_lae)
        self.daorumoxin_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.daorumoxin_lae.setFont(font)
        self.daorumoxin_lae.setObjectName("daorumoxin_lae")
        self.horizontalLayout_10.addWidget(self.daorumoxin_lae)
        self.xunlian_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunlian_lae.setFont(font)
        self.xunlian_lae.setObjectName("xunlian_lae")
        self.horizontalLayout_10.addWidget(self.xunlian_lae)
        self.xunliantezheng_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.xunliantezheng_lae.setFont(font)
        self.xunliantezheng_lae.setObjectName("xunliantezheng_lae")
        self.horizontalLayout_10.addWidget(self.xunliantezheng_lae)
        self.baocunmoxin_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunmoxin_lae.setFont(font)
        self.baocunmoxin_lae.setObjectName("baocunmoxin_lae")
        self.horizontalLayout_10.addWidget(self.baocunmoxin_lae)
        self.ceshitezheng_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.ceshitezheng_lae.setFont(font)
        self.ceshitezheng_lae.setObjectName("ceshitezheng_lae")
        self.horizontalLayout_10.addWidget(self.ceshitezheng_lae)
        self.baocunshuju_lae = QtWidgets.QPushButton(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.baocunshuju_lae.setFont(font)
        self.baocunshuju_lae.setObjectName("baocunshuju_lae")
        self.horizontalLayout_10.addWidget(self.baocunshuju_lae)
        self.gridLayout.addLayout(self.horizontalLayout_10, 1, 0, 1, 11)
        self.label_xunlianwucha_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_xunlianwucha_lae.setFont(font)
        self.label_xunlianwucha_lae.setObjectName("label_xunlianwucha_lae")
        self.gridLayout.addWidget(self.label_xunlianwucha_lae, 2, 1, 1, 3, QtCore.Qt.AlignHCenter)
        self.label_tezhengshuju_lae = QtWidgets.QLabel(self.page_LAE)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_tezhengshuju_lae.setFont(font)
        self.label_tezhengshuju_lae.setObjectName("label_tezhengshuju_lae")
        self.gridLayout.addWidget(self.label_tezhengshuju_lae, 2, 8, 1, 1, QtCore.Qt.AlignHCenter)
        self.history_lae = QtWidgets.QWidget(self.page_LAE)
        self.history_lae.setObjectName("history_lae")
        self.gridLayout.addWidget(self.history_lae, 3, 0, 1, 5)
        self.LAE_features = QtWidgets.QTableWidget(self.page_LAE)
        self.LAE_features.setObjectName("LAE_features")
        self.LAE_features.setColumnCount(0)
        self.LAE_features.setRowCount(0)
        self.gridLayout.addWidget(self.LAE_features, 3, 5, 1, 6)
        self.stackedWidget.addWidget(self.page_LAE)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 8)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1170, 23))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.traindata = QtWidgets.QAction(MainWindow)
        self.traindata.setObjectName("traindata")
        self.load_test = QtWidgets.QAction(MainWindow)
        self.load_test.setObjectName("load_test")
        self.testdata = QtWidgets.QAction(MainWindow)
        self.testdata.setObjectName("testdata")
        self.menu_1.addAction(self.traindata)
        self.menu_1.addAction(self.testdata)
        self.menubar.addAction(self.menu_1.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.button_pca.setText(_translate("MainWindow", "PCA"))
        self.label_xunlianshuju.setText(_translate("MainWindow", " 训练数据"))
        self.button_ae.setText(_translate("MainWindow", "AE"))
        self.button_lae.setText(_translate("MainWindow", "labelAE"))
        self.button_kpca.setText(_translate("MainWindow", "KPCA"))
        self.button_kpls.setText(_translate("MainWindow", "KPLS"))
        self.button_pls.setText(_translate("MainWindow", "PLS"))
        self.button_sae.setText(_translate("MainWindow", "sparseAE"))
        self.button_dae.setText(_translate("MainWindow", "denoiseAE"))
        self.label_ceshishuju.setText(_translate("MainWindow", "测试数据"))
        self.label_n_components_pca.setToolTip(_translate("MainWindow", "目标维度"))
        self.label_n_components_pca.setText(_translate("MainWindow", "n_components"))
        self.n_components_pca.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.Pre_Processing_pca.setToolTip(_translate("MainWindow", "对原始数据进行预处理"))
        self.Pre_Processing_pca.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_pca.setToolTip(_translate("MainWindow", "对数据进行PCA建模"))
        self.xunlian_pca.setText(_translate("MainWindow", "训练模型"))
        self.xunliantezheng_pca.setToolTip(_translate("MainWindow", "提取训练数据的PCA特征"))
        self.xunliantezheng_pca.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxing_pca.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_pca.setText(_translate("MainWindow", "导入模型"))
        self.ceshitezheng_pca.setToolTip(_translate("MainWindow", "提取测试数据的PCA特征"))
        self.ceshitezheng_pca.setText(_translate("MainWindow", "测试特征"))
        self.baocunshujv_pca.setToolTip(_translate("MainWindow", "保存特征数据"))
        self.baocunshujv_pca.setText(_translate("MainWindow", "保存数据"))
        self.label_tezhenggongxiantu_pca.setText(_translate("MainWindow", "PCA特征贡献图"))
        self.label_tezhengshujv_pca.setText(_translate("MainWindow", "特征数据"))
        self.label_n_components_pls.setToolTip(_translate("MainWindow", "目标维度"))
        self.label_n_components_pls.setText(_translate("MainWindow", "n_components"))
        self.n_components_pls.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_biaoqianlieshu_pls.setToolTip(_translate("MainWindow", "标签数量"))
        self.label_biaoqianlieshu_pls.setText(_translate("MainWindow", "标签列数"))
        self.biaoqianlieshu_pls.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.Pre_Processing_pls.setToolTip(_translate("MainWindow", "对原始数据进行预处理"))
        self.Pre_Processing_pls.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_pls.setToolTip(_translate("MainWindow", "对数据进行PLS建模"))
        self.xunlian_pls.setText(_translate("MainWindow", "训练模型"))
        self.xunliantezheng_pls.setToolTip(_translate("MainWindow", "提取训练数据的PLS特征"))
        self.xunliantezheng_pls.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxing_pls.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_pls.setText(_translate("MainWindow", "导入模型"))
        self.ceshitezheng_pls.setToolTip(_translate("MainWindow", "提取测试数据的PLS特征"))
        self.ceshitezheng_pls.setText(_translate("MainWindow", "测试特征"))
        self.baocunshujv_pls.setToolTip(_translate("MainWindow", "保存特征数据"))
        self.baocunshujv_pls.setText(_translate("MainWindow", "保存数据"))
        self.tezhenggongxiantu_pls.setText(_translate("MainWindow", "PLS特征贡献图"))
        self.tezhengshujv_pls.setText(_translate("MainWindow", "特征数据"))
        self.label_tezhenggonxiantu_kpca.setText(_translate("MainWindow", "KPCA特征贡献图"))
        self.label_n_components_kpca.setToolTip(_translate("MainWindow", "目标维度"))
        self.label_n_components_kpca.setText(_translate("MainWindow", "n_components"))
        self.n_components_kpca.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.n_components_kpca.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_kernel_function_kpca.setToolTip(_translate("MainWindow", "映射核函数"))
        self.label_kernel_function_kpca.setText(_translate("MainWindow", "kernel_function"))
        self.kernel_function_kpca.setItemText(0, _translate("MainWindow", "linear"))
        self.kernel_function_kpca.setItemText(1, _translate("MainWindow", "poly"))
        self.kernel_function_kpca.setItemText(2, _translate("MainWindow", "rbf"))
        self.kernel_function_kpca.setItemText(3, _translate("MainWindow", "sigmoid"))
        self.kernel_function_kpca.setItemText(4, _translate("MainWindow", "cosine"))
        self.label_nkernel_components_kpca.setToolTip(_translate("MainWindow", "映射后的数据维度"))
        self.label_nkernel_components_kpca.setText(_translate("MainWindow", "nkernel_components"))
        self.nkernel_components_kpca.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.Pre_Processing_kpca.setToolTip(_translate("MainWindow", "对原始数据进行预处理"))
        self.Pre_Processing_kpca.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_kpca.setToolTip(_translate("MainWindow", "对数据进行KPCA建模"))
        self.xunlian_kpca.setText(_translate("MainWindow", "训练模型"))
        self.xunliantezheng_kpca.setToolTip(_translate("MainWindow", "提取训练数据的KPCA特征"))
        self.xunliantezheng_kpca.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxing_kpca.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_kpca.setText(_translate("MainWindow", "导入模型"))
        self.ceshitezheng_kpca.setToolTip(_translate("MainWindow", "提取测试数据的KPCA特征"))
        self.ceshitezheng_kpca.setText(_translate("MainWindow", "测试特征"))
        self.baocunshujv_kpca.setToolTip(_translate("MainWindow", "保存特征数据"))
        self.baocunshujv_kpca.setText(_translate("MainWindow", "保存数据"))
        self.label_tezhengshujv_kpca.setText(_translate("MainWindow", "特征数据"))
        self.label_n_components_kpls.setToolTip(_translate("MainWindow", "目标维度"))
        self.label_n_components_kpls.setText(_translate("MainWindow", "n_components"))
        self.n_components_kpls.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_biaoqianlieshu_kpls.setToolTip(_translate("MainWindow", "标签数量"))
        self.label_biaoqianlieshu_kpls.setText(_translate("MainWindow", "标签列数"))
        self.biaoqianlieshu_kpls.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.label_kernel_function_kpls.setToolTip(_translate("MainWindow", "映射核函数"))
        self.label_kernel_function_kpls.setText(_translate("MainWindow", "kernel_function"))
        self.kernel_function_kpls.setItemText(0, _translate("MainWindow", "linear"))
        self.kernel_function_kpls.setItemText(1, _translate("MainWindow", "poly"))
        self.kernel_function_kpls.setItemText(2, _translate("MainWindow", "rbf"))
        self.kernel_function_kpls.setItemText(3, _translate("MainWindow", "sigmoid"))
        self.kernel_function_kpls.setItemText(4, _translate("MainWindow", "cosine"))
        self.label_nkernel_components_kpls.setToolTip(_translate("MainWindow", "映射后的数据维度"))
        self.label_nkernel_components_kpls.setText(_translate("MainWindow", "nkernel_components"))
        self.nkernel_components_kpls.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.Pre_Processing_kpls.setToolTip(_translate("MainWindow", "对原始数据进行预处理"))
        self.Pre_Processing_kpls.setText(_translate("MainWindow", "Pre-Processing"))
        self.label_tezhengshujv_pls.setText(_translate("MainWindow", "特征数据"))
        self.label_tezhenggonxiantu_kpls.setText(_translate("MainWindow", "KPLS特征贡献图"))
        self.xunlian_kpls.setToolTip(_translate("MainWindow", "对数据进行KPLS建模"))
        self.xunlian_kpls.setText(_translate("MainWindow", "训练模型"))
        self.xunliantezheng_kpls.setToolTip(_translate("MainWindow", "提取训练数据的KPLS特征"))
        self.xunliantezheng_kpls.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxing_kpls.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_kpls.setText(_translate("MainWindow", "导入模型"))
        self.ceshitezheng_kpls.setToolTip(_translate("MainWindow", "提取测试数据的KPLS特征"))
        self.ceshitezheng_kpls.setText(_translate("MainWindow", "测试特征"))
        self.baocunshujv_kpls.setToolTip(_translate("MainWindow", "保存特征数据"))
        self.baocunshujv_kpls.setText(_translate("MainWindow", "保存数据"))
        self.label_yincengjiegou_ae.setText(_translate("MainWindow", "隐层结构："))
        self.structure_ae.setText(_translate("MainWindow", "[30, 20, 30]"))
        self.structure_ae.setPlaceholderText(_translate("MainWindow", "[30, 20, 30]"))
        self.label_epoch_ae.setText(_translate("MainWindow", "Epoch："))
        self.epoch_ae.setText(_translate("MainWindow", "1000"))
        self.epoch_ae.setPlaceholderText(_translate("MainWindow", "1000"))
        self.label_batchsize_ae.setText(_translate("MainWindow", "Batch_size："))
        self.batchsize_ae.setText(_translate("MainWindow", "50"))
        self.batchsize_ae.setPlaceholderText(_translate("MainWindow", "50"))
        self.earlystop_ae.setText(_translate("MainWindow", " EarlyStopping"))
        self.chushihua_ae.setText(_translate("MainWindow", "初始化模型"))
        self.daorumoxin_ae.setText(_translate("MainWindow", "导入模型"))
        self.xunlian_ae.setText(_translate("MainWindow", "重新训练"))
        self.xunliantezheng_ae.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxin_ae.setText(_translate("MainWindow", "保存模型"))
        self.ceshitezheng_ae.setText(_translate("MainWindow", "测试特征"))
        self.baocunshuju_ae.setText(_translate("MainWindow", "保存数据"))
        self.label_xunlianwucha_ae_.setText(_translate("MainWindow", "AE 训练误差"))
        self.label_tezhengshuju_ae.setText(_translate("MainWindow", "特征数据"))
        self.label_yincengjiegou_sae.setText(_translate("MainWindow", "隐层结构："))
        self.structure_sae.setText(_translate("MainWindow", "[30, 40, 30]"))
        self.structure_sae.setPlaceholderText(_translate("MainWindow", "[30, 20, 30]"))
        self.label_epoch_sae.setText(_translate("MainWindow", "Epoch："))
        self.epoch_sae.setText(_translate("MainWindow", "1000"))
        self.epoch_sae.setPlaceholderText(_translate("MainWindow", "1000"))
        self.label_batchsize_sae.setText(_translate("MainWindow", "Batch_size："))
        self.batchsize_sae.setText(_translate("MainWindow", "50"))
        self.batchsize_sae.setPlaceholderText(_translate("MainWindow", "50"))
        self.earlystop_sae.setText(_translate("MainWindow", " EarlyStopping"))
        self.chushihua_sae.setText(_translate("MainWindow", "初始化模型"))
        self.daorumoxin_sae.setText(_translate("MainWindow", "导入模型"))
        self.xunlian_sae.setText(_translate("MainWindow", "重新训练"))
        self.xunliantezheng_sae.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxin_sae.setText(_translate("MainWindow", "保存模型"))
        self.ceshitezheng_sae.setText(_translate("MainWindow", "测试特征"))
        self.baocunshuju_sae.setText(_translate("MainWindow", "保存数据"))
        self.label_xunlianwucha_sae.setText(_translate("MainWindow", "sparseAE 训练误差"))
        self.label_tezhengshuju_sae.setText(_translate("MainWindow", "特征数据"))
        self.label_yincengjiegou_dae.setText(_translate("MainWindow", "隐层结构："))
        self.structure_dae.setText(_translate("MainWindow", "[30, 40, 30]"))
        self.structure_dae.setPlaceholderText(_translate("MainWindow", "[30, 20, 30]"))
        self.label_epoch_dae.setText(_translate("MainWindow", "Epoch："))
        self.epoch_dae.setText(_translate("MainWindow", "1000"))
        self.epoch_dae.setPlaceholderText(_translate("MainWindow", "1000"))
        self.label_batchsize_dae.setText(_translate("MainWindow", "Batch_size："))
        self.batchsize_dae.setText(_translate("MainWindow", "50"))
        self.batchsize_dae.setPlaceholderText(_translate("MainWindow", "50"))
        self.label_corrupt_dae.setText(_translate("MainWindow", "Corrupt rate："))
        self.corrupt_dae.setText(_translate("MainWindow", "0.5"))
        self.corrupt_dae.setPlaceholderText(_translate("MainWindow", "50"))
        self.earlystop_dae.setText(_translate("MainWindow", " EarlyStopping"))
        self.chushihua_dae.setText(_translate("MainWindow", "初始化模型"))
        self.daorumoxin_dae.setText(_translate("MainWindow", "导入模型"))
        self.xunlian_dae.setText(_translate("MainWindow", "重新训练"))
        self.xunliantezheng_dae.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxin_dae.setText(_translate("MainWindow", "保存模型"))
        self.ceshitezheng_dae.setText(_translate("MainWindow", "测试特征"))
        self.baocunshuju_dae.setText(_translate("MainWindow", "保存数据"))
        self.label_xunlianwucha_dae.setText(_translate("MainWindow", "denoiseAE 训练误差"))
        self.label_tezhengshuju_dae.setText(_translate("MainWindow", "特征数据"))
        self.label_yincengjiegou_lae.setText(_translate("MainWindow", "隐层结构："))
        self.structure_lae.setText(_translate("MainWindow", "[30, 40, 30]"))
        self.structure_lae.setPlaceholderText(_translate("MainWindow", "[30, 20, 30]"))
        self.label_epoch_lae.setText(_translate("MainWindow", "Epoch："))
        self.epoch_lae.setText(_translate("MainWindow", "1000"))
        self.epoch_lae.setPlaceholderText(_translate("MainWindow", "1000"))
        self.label_batchsize_lae.setText(_translate("MainWindow", "Batch_size："))
        self.batchsize_lae.setText(_translate("MainWindow", "50"))
        self.batchsize_lae.setPlaceholderText(_translate("MainWindow", "50"))
        self.label_zuoyong_lae.setText(_translate("MainWindow", "作用："))
        self.zuoyong_lae.setItemText(0, _translate("MainWindow", "分类"))
        self.zuoyong_lae.setItemText(1, _translate("MainWindow", "回归"))
        self.label_biaoqianlieshu_lae.setText(_translate("MainWindow", "标签列数："))
        self.biaoqianlieshu_lae.setText(_translate("MainWindow", "1"))
        self.biaoqianlieshu_lae.setPlaceholderText(_translate("MainWindow", "50"))
        self.earlystop_lae.setText(_translate("MainWindow", " EarlyStopping"))
        self.chushihua_lae.setText(_translate("MainWindow", "初始化模型"))
        self.daorumoxin_lae.setText(_translate("MainWindow", "导入模型"))
        self.xunlian_lae.setText(_translate("MainWindow", "重新训练"))
        self.xunliantezheng_lae.setText(_translate("MainWindow", "训练特征"))
        self.baocunmoxin_lae.setText(_translate("MainWindow", "保存模型"))
        self.ceshitezheng_lae.setText(_translate("MainWindow", "测试特征"))
        self.baocunshuju_lae.setText(_translate("MainWindow", "保存数据"))
        self.label_xunlianwucha_lae.setText(_translate("MainWindow", "labelAE 训练误差"))
        self.label_tezhengshuju_lae.setText(_translate("MainWindow", "特征数据"))
        self.menu_1.setTitle(_translate("MainWindow", "数据"))
        self.traindata.setText(_translate("MainWindow", "Train_DATA"))
        self.load_test.setText(_translate("MainWindow", "Testing data"))
        self.testdata.setText(_translate("MainWindow", "Test_DATA"))

