# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Window.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(915, 594)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_xunlianshuju = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_xunlianshuju.setFont(font)
        self.label_xunlianshuju.setObjectName("label_xunlianshuju")
        self.gridLayout_2.addWidget(self.label_xunlianshuju, 0, 1, 1, 1)
        self.label_ceshishuju = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_ceshishuju.setFont(font)
        self.label_ceshishuju.setObjectName("label_ceshishuju")
        self.gridLayout_2.addWidget(self.label_ceshishuju, 0, 3, 1, 1)
        self.trainWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.trainWidget.setObjectName("trainWidget")
        self.trainWidget.setColumnCount(0)
        self.trainWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.trainWidget, 1, 0, 1, 2)
        self.testWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.testWidget.setObjectName("testWidget")
        self.testWidget.setColumnCount(0)
        self.testWidget.setRowCount(0)
        self.gridLayout_2.addWidget(self.testWidget, 1, 2, 1, 2)
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_KMeans = QtWidgets.QWidget()
        self.page_KMeans.setObjectName("page_KMeans")
        self.gridLayout = QtWidgets.QGridLayout(self.page_KMeans)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_n_clusters_kmeans = QtWidgets.QLabel(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_n_clusters_kmeans.setFont(font)
        self.label_n_clusters_kmeans.setObjectName("label_n_clusters_kmeans")
        self.horizontalLayout.addWidget(self.label_n_clusters_kmeans)
        self.n_clusters_kmeans = QtWidgets.QLineEdit(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.n_clusters_kmeans.setFont(font)
        self.n_clusters_kmeans.setObjectName("n_clusters_kmeans")
        self.horizontalLayout.addWidget(self.n_clusters_kmeans)
        self.Pre_Processing_kmeans = QtWidgets.QRadioButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Pre_Processing_kmeans.setFont(font)
        self.Pre_Processing_kmeans.setChecked(True)
        self.Pre_Processing_kmeans.setObjectName("Pre_Processing_kmeans")
        self.horizontalLayout.addWidget(self.Pre_Processing_kmeans)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.xunlian_kmeans = QtWidgets.QPushButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.xunlian_kmeans.setFont(font)
        self.xunlian_kmeans.setObjectName("xunlian_kmeans")
        self.horizontalLayout_2.addWidget(self.xunlian_kmeans)
        self.xunlianjieguo_kmeans = QtWidgets.QPushButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.xunlianjieguo_kmeans.setFont(font)
        self.xunlianjieguo_kmeans.setObjectName("xunlianjieguo_kmeans")
        self.horizontalLayout_2.addWidget(self.xunlianjieguo_kmeans)
        self.baocunmoxing_kmeans = QtWidgets.QPushButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baocunmoxing_kmeans.setFont(font)
        self.baocunmoxing_kmeans.setObjectName("baocunmoxing_kmeans")
        self.horizontalLayout_2.addWidget(self.baocunmoxing_kmeans)
        self.daorumoxing_kmeans = QtWidgets.QPushButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.daorumoxing_kmeans.setFont(font)
        self.daorumoxing_kmeans.setObjectName("daorumoxing_kmeans")
        self.horizontalLayout_2.addWidget(self.daorumoxing_kmeans)
        self.ceshijieguo_kmeans = QtWidgets.QPushButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ceshijieguo_kmeans.setFont(font)
        self.ceshijieguo_kmeans.setObjectName("ceshijieguo_kmeans")
        self.horizontalLayout_2.addWidget(self.ceshijieguo_kmeans)
        self.baocunshuju_kmeans = QtWidgets.QPushButton(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baocunshuju_kmeans.setFont(font)
        self.baocunshuju_kmeans.setObjectName("baocunshuju_kmeans")
        self.horizontalLayout_2.addWidget(self.baocunshuju_kmeans)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 2)
        self.label_xunlianjieguo_kmeans = QtWidgets.QLabel(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_xunlianjieguo_kmeans.setFont(font)
        self.label_xunlianjieguo_kmeans.setObjectName("label_xunlianjieguo_kmeans")
        self.gridLayout.addWidget(self.label_xunlianjieguo_kmeans, 2, 0, 1, 1)
        self.label_ceshijieguo_kmeans = QtWidgets.QLabel(self.page_KMeans)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_ceshijieguo_kmeans.setFont(font)
        self.label_ceshijieguo_kmeans.setObjectName("label_ceshijieguo_kmeans")
        self.gridLayout.addWidget(self.label_ceshijieguo_kmeans, 2, 1, 1, 1)
        self.kmeans_xunlianjieguo = QtWidgets.QTableWidget(self.page_KMeans)
        self.kmeans_xunlianjieguo.setObjectName("kmeans_xunlianjieguo")
        self.kmeans_xunlianjieguo.setColumnCount(0)
        self.kmeans_xunlianjieguo.setRowCount(0)
        self.gridLayout.addWidget(self.kmeans_xunlianjieguo, 3, 0, 1, 1)
        self.kmeans_ceshijieguo = QtWidgets.QTableWidget(self.page_KMeans)
        self.kmeans_ceshijieguo.setObjectName("kmeans_ceshijieguo")
        self.kmeans_ceshijieguo.setColumnCount(0)
        self.kmeans_ceshijieguo.setRowCount(0)
        self.gridLayout.addWidget(self.kmeans_ceshijieguo, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_KMeans)
        self.page_GMM = QtWidgets.QWidget()
        self.page_GMM.setObjectName("page_GMM")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_GMM)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_n_components_gmm = QtWidgets.QLabel(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_n_components_gmm.setFont(font)
        self.label_n_components_gmm.setObjectName("label_n_components_gmm")
        self.horizontalLayout_3.addWidget(self.label_n_components_gmm)
        self.n_components_min_gmm = QtWidgets.QLineEdit(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.n_components_min_gmm.setFont(font)
        self.n_components_min_gmm.setObjectName("n_components_min_gmm")
        self.horizontalLayout_3.addWidget(self.n_components_min_gmm)
        self.label_to_gmm = QtWidgets.QLabel(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_to_gmm.setFont(font)
        self.label_to_gmm.setObjectName("label_to_gmm")
        self.horizontalLayout_3.addWidget(self.label_to_gmm)
        self.n_components_max_gmm = QtWidgets.QLineEdit(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.n_components_max_gmm.setFont(font)
        self.n_components_max_gmm.setObjectName("n_components_max_gmm")
        self.horizontalLayout_3.addWidget(self.n_components_max_gmm)
        self.label_covariance_type_gmm = QtWidgets.QLabel(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_covariance_type_gmm.setFont(font)
        self.label_covariance_type_gmm.setObjectName("label_covariance_type_gmm")
        self.horizontalLayout_3.addWidget(self.label_covariance_type_gmm)
        self.comboBox_covariance_type_gmm = QtWidgets.QComboBox(self.page_GMM)
        self.comboBox_covariance_type_gmm.setObjectName("comboBox_covariance_type_gmm")
        self.comboBox_covariance_type_gmm.addItem("")
        self.comboBox_covariance_type_gmm.addItem("")
        self.comboBox_covariance_type_gmm.addItem("")
        self.comboBox_covariance_type_gmm.addItem("")
        self.comboBox_covariance_type_gmm.addItem("")
        self.horizontalLayout_3.addWidget(self.comboBox_covariance_type_gmm)
        self.Pre_Processing_gmm = QtWidgets.QRadioButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Pre_Processing_gmm.setFont(font)
        self.Pre_Processing_gmm.setChecked(True)
        self.Pre_Processing_gmm.setObjectName("Pre_Processing_gmm")
        self.horizontalLayout_3.addWidget(self.Pre_Processing_gmm)
        self.gridLayout_3.addLayout(self.horizontalLayout_3, 0, 0, 1, 2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.xunlian_gmm = QtWidgets.QPushButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.xunlian_gmm.setFont(font)
        self.xunlian_gmm.setObjectName("xunlian_gmm")
        self.horizontalLayout_4.addWidget(self.xunlian_gmm)
        self.xunlianjieguo_gmm = QtWidgets.QPushButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.xunlianjieguo_gmm.setFont(font)
        self.xunlianjieguo_gmm.setObjectName("xunlianjieguo_gmm")
        self.horizontalLayout_4.addWidget(self.xunlianjieguo_gmm)
        self.baocunmoxing_gmm = QtWidgets.QPushButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baocunmoxing_gmm.setFont(font)
        self.baocunmoxing_gmm.setObjectName("baocunmoxing_gmm")
        self.horizontalLayout_4.addWidget(self.baocunmoxing_gmm)
        self.daorumoxing_gmm = QtWidgets.QPushButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.daorumoxing_gmm.setFont(font)
        self.daorumoxing_gmm.setObjectName("daorumoxing_gmm")
        self.horizontalLayout_4.addWidget(self.daorumoxing_gmm)
        self.ceshijieguo_gmm = QtWidgets.QPushButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ceshijieguo_gmm.setFont(font)
        self.ceshijieguo_gmm.setObjectName("ceshijieguo_gmm")
        self.horizontalLayout_4.addWidget(self.ceshijieguo_gmm)
        self.baocunshuju_gmm = QtWidgets.QPushButton(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baocunshuju_gmm.setFont(font)
        self.baocunshuju_gmm.setObjectName("baocunshuju_gmm")
        self.horizontalLayout_4.addWidget(self.baocunshuju_gmm)
        self.gridLayout_3.addLayout(self.horizontalLayout_4, 1, 0, 1, 2)
        self.label_beiyesi_gmm = QtWidgets.QLabel(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_beiyesi_gmm.setFont(font)
        self.label_beiyesi_gmm.setObjectName("label_beiyesi_gmm")
        self.gridLayout_3.addWidget(self.label_beiyesi_gmm, 2, 0, 1, 1)
        self.label_juleijieguo_gmm = QtWidgets.QLabel(self.page_GMM)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_juleijieguo_gmm.setFont(font)
        self.label_juleijieguo_gmm.setObjectName("label_juleijieguo_gmm")
        self.gridLayout_3.addWidget(self.label_juleijieguo_gmm, 2, 1, 1, 1)
        self.gmm_beiyesi = QtWidgets.QGraphicsView(self.page_GMM)
        self.gmm_beiyesi.setObjectName("gmm_beiyesi")
        self.gridLayout_3.addWidget(self.gmm_beiyesi, 3, 0, 1, 1)
        self.gmm_juleijieguo = QtWidgets.QTableWidget(self.page_GMM)
        self.gmm_juleijieguo.setObjectName("gmm_juleijieguo")
        self.gmm_juleijieguo.setColumnCount(0)
        self.gmm_juleijieguo.setRowCount(0)
        self.gridLayout_3.addWidget(self.gmm_juleijieguo, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_GMM)
        self.page_HCC = QtWidgets.QWidget()
        self.page_HCC.setObjectName("page_HCC")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.page_HCC)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_pandingxuanze_hcc = QtWidgets.QLabel(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_pandingxuanze_hcc.setFont(font)
        self.label_pandingxuanze_hcc.setObjectName("label_pandingxuanze_hcc")
        self.horizontalLayout_6.addWidget(self.label_pandingxuanze_hcc)
        self.comboBox_criterion_hcc = QtWidgets.QComboBox(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.comboBox_criterion_hcc.setFont(font)
        self.comboBox_criterion_hcc.setObjectName("comboBox_criterion_hcc")
        self.comboBox_criterion_hcc.addItem("")
        self.comboBox_criterion_hcc.addItem("")
        self.comboBox_criterion_hcc.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_criterion_hcc)
        self.line_criterion_hcc = QtWidgets.QLineEdit(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.line_criterion_hcc.setFont(font)
        self.line_criterion_hcc.setObjectName("line_criterion_hcc")
        self.horizontalLayout_6.addWidget(self.line_criterion_hcc)
        self.label_linkage_hcc = QtWidgets.QLabel(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_linkage_hcc.setFont(font)
        self.label_linkage_hcc.setObjectName("label_linkage_hcc")
        self.horizontalLayout_6.addWidget(self.label_linkage_hcc)
        self.comboBox_linkage_hcc = QtWidgets.QComboBox(self.page_HCC)
        self.comboBox_linkage_hcc.setObjectName("comboBox_linkage_hcc")
        self.comboBox_linkage_hcc.addItem("")
        self.comboBox_linkage_hcc.addItem("")
        self.comboBox_linkage_hcc.addItem("")
        self.comboBox_linkage_hcc.addItem("")
        self.horizontalLayout_6.addWidget(self.comboBox_linkage_hcc)
        self.Pre_Processing_hcc = QtWidgets.QRadioButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.Pre_Processing_hcc.setFont(font)
        self.Pre_Processing_hcc.setChecked(True)
        self.Pre_Processing_hcc.setObjectName("Pre_Processing_hcc")
        self.horizontalLayout_6.addWidget(self.Pre_Processing_hcc)
        self.gridLayout_4.addLayout(self.horizontalLayout_6, 0, 0, 1, 2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.xunlian_hcc = QtWidgets.QPushButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.xunlian_hcc.setFont(font)
        self.xunlian_hcc.setObjectName("xunlian_hcc")
        self.horizontalLayout_5.addWidget(self.xunlian_hcc)
        self.xunlianjieguo_hcc = QtWidgets.QPushButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.xunlianjieguo_hcc.setFont(font)
        self.xunlianjieguo_hcc.setObjectName("xunlianjieguo_hcc")
        self.horizontalLayout_5.addWidget(self.xunlianjieguo_hcc)
        self.baocunmoxing_hcc = QtWidgets.QPushButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baocunmoxing_hcc.setFont(font)
        self.baocunmoxing_hcc.setObjectName("baocunmoxing_hcc")
        self.horizontalLayout_5.addWidget(self.baocunmoxing_hcc)
        self.daorumoxing_hcc = QtWidgets.QPushButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.daorumoxing_hcc.setFont(font)
        self.daorumoxing_hcc.setObjectName("daorumoxing_hcc")
        self.horizontalLayout_5.addWidget(self.daorumoxing_hcc)
        self.ceshijieguo_hcc = QtWidgets.QPushButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.ceshijieguo_hcc.setFont(font)
        self.ceshijieguo_hcc.setObjectName("ceshijieguo_hcc")
        self.horizontalLayout_5.addWidget(self.ceshijieguo_hcc)
        self.baocunshuju_hcc = QtWidgets.QPushButton(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.baocunshuju_hcc.setFont(font)
        self.baocunshuju_hcc.setObjectName("baocunshuju_hcc")
        self.horizontalLayout_5.addWidget(self.baocunshuju_hcc)
        self.gridLayout_4.addLayout(self.horizontalLayout_5, 1, 0, 1, 2)
        self.label_shuzhuangtu_hcc = QtWidgets.QLabel(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_shuzhuangtu_hcc.setFont(font)
        self.label_shuzhuangtu_hcc.setObjectName("label_shuzhuangtu_hcc")
        self.gridLayout_4.addWidget(self.label_shuzhuangtu_hcc, 2, 0, 1, 1)
        self.label_juleijieguo_hcc = QtWidgets.QLabel(self.page_HCC)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.label_juleijieguo_hcc.setFont(font)
        self.label_juleijieguo_hcc.setObjectName("label_juleijieguo_hcc")
        self.gridLayout_4.addWidget(self.label_juleijieguo_hcc, 2, 1, 1, 1)
        self.hcc_shuzhuangtu = QtWidgets.QGraphicsView(self.page_HCC)
        self.hcc_shuzhuangtu.setObjectName("hcc_shuzhuangtu")
        self.gridLayout_4.addWidget(self.hcc_shuzhuangtu, 3, 0, 1, 1)
        self.hcc_juleijieguo = QtWidgets.QTableWidget(self.page_HCC)
        self.hcc_juleijieguo.setObjectName("hcc_juleijieguo")
        self.hcc_juleijieguo.setColumnCount(0)
        self.hcc_juleijieguo.setRowCount(0)
        self.gridLayout_4.addWidget(self.hcc_juleijieguo, 3, 1, 1, 1)
        self.stackedWidget.addWidget(self.page_HCC)
        self.gridLayout_2.addWidget(self.stackedWidget, 2, 0, 1, 4)
        self.button_kmeans = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.button_kmeans.setFont(font)
        self.button_kmeans.setObjectName("button_kmeans")
        self.gridLayout_2.addWidget(self.button_kmeans, 3, 0, 1, 1)
        self.button_gmm = QtWidgets.QPushButton(self.centralwidget)
        self.button_gmm.setObjectName("button_gmm")
        self.gridLayout_2.addWidget(self.button_gmm, 3, 1, 1, 1)
        self.button_hcc = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        self.button_hcc.setFont(font)
        self.button_hcc.setObjectName("button_hcc")
        self.gridLayout_2.addWidget(self.button_hcc, 3, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 915, 23))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.traindata = QtWidgets.QAction(MainWindow)
        self.traindata.setObjectName("traindata")
        self.testdata = QtWidgets.QAction(MainWindow)
        self.testdata.setObjectName("testdata")
        self.menu_1.addAction(self.traindata)
        self.menu_1.addAction(self.testdata)
        self.menubar.addAction(self.menu_1.menuAction())

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_xunlianshuju.setText(_translate("MainWindow", "训练数据"))
        self.label_ceshishuju.setText(_translate("MainWindow", "测试数据"))
        self.label_n_clusters_kmeans.setText(_translate("MainWindow", "n_clusters"))
        self.n_clusters_kmeans.setPlaceholderText(_translate("MainWindow", "请输入正整数"))
        self.Pre_Processing_kmeans.setToolTip(_translate("MainWindow", "对原始数据进行预处理"))
        self.Pre_Processing_kmeans.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_kmeans.setText(_translate("MainWindow", "训练模型"))
        self.xunlianjieguo_kmeans.setText(_translate("MainWindow", "训练结果"))
        self.baocunmoxing_kmeans.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_kmeans.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_kmeans.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_kmeans.setText(_translate("MainWindow", "保存数据"))
        self.label_xunlianjieguo_kmeans.setText(_translate("MainWindow", "训练数据的K-Means聚类结果"))
        self.label_ceshijieguo_kmeans.setText(_translate("MainWindow", "测试数据的K-Means聚类结果"))
        self.label_n_components_gmm.setText(_translate("MainWindow", "n_components"))
        self.n_components_min_gmm.setPlaceholderText(_translate("MainWindow", "最小值"))
        self.label_to_gmm.setText(_translate("MainWindow", "to"))
        self.n_components_max_gmm.setPlaceholderText(_translate("MainWindow", "最大值"))
        self.label_covariance_type_gmm.setText(_translate("MainWindow", "covariance_type"))
        self.comboBox_covariance_type_gmm.setItemText(0, _translate("MainWindow", "full"))
        self.comboBox_covariance_type_gmm.setItemText(1, _translate("MainWindow", "tied"))
        self.comboBox_covariance_type_gmm.setItemText(2, _translate("MainWindow", "diag"))
        self.comboBox_covariance_type_gmm.setItemText(3, _translate("MainWindow", "spherical"))
        self.comboBox_covariance_type_gmm.setItemText(4, _translate("MainWindow", "auto"))
        self.Pre_Processing_gmm.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_gmm.setText(_translate("MainWindow", "训练模型"))
        self.xunlianjieguo_gmm.setText(_translate("MainWindow", "训练结果"))
        self.baocunmoxing_gmm.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_gmm.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_gmm.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_gmm.setText(_translate("MainWindow", "保存数据"))
        self.label_beiyesi_gmm.setText(_translate("MainWindow", "GMM贝叶斯信息准则"))
        self.label_juleijieguo_gmm.setText(_translate("MainWindow", "GMM聚类结果"))
        self.label_pandingxuanze_hcc.setText(_translate("MainWindow", "判定标准："))
        self.comboBox_criterion_hcc.setItemText(0, _translate("MainWindow", "inconsistent"))
        self.comboBox_criterion_hcc.setItemText(1, _translate("MainWindow", "distance"))
        self.comboBox_criterion_hcc.setItemText(2, _translate("MainWindow", "maxclust"))
        self.line_criterion_hcc.setPlaceholderText(_translate("MainWindow", "请输入0~1的数"))
        self.label_linkage_hcc.setText(_translate("MainWindow", "linkage："))
        self.comboBox_linkage_hcc.setItemText(0, _translate("MainWindow", "single"))
        self.comboBox_linkage_hcc.setItemText(1, _translate("MainWindow", "complete"))
        self.comboBox_linkage_hcc.setItemText(2, _translate("MainWindow", "average"))
        self.comboBox_linkage_hcc.setItemText(3, _translate("MainWindow", "ward"))
        self.Pre_Processing_hcc.setText(_translate("MainWindow", "Pre-Processing"))
        self.xunlian_hcc.setText(_translate("MainWindow", "训练模型"))
        self.xunlianjieguo_hcc.setText(_translate("MainWindow", "训练结果"))
        self.baocunmoxing_hcc.setText(_translate("MainWindow", "保存模型"))
        self.daorumoxing_hcc.setText(_translate("MainWindow", "导入模型"))
        self.ceshijieguo_hcc.setText(_translate("MainWindow", "测试结果"))
        self.baocunshuju_hcc.setText(_translate("MainWindow", "保存数据"))
        self.label_shuzhuangtu_hcc.setText(_translate("MainWindow", "层次聚类树状图"))
        self.label_juleijieguo_hcc.setText(_translate("MainWindow", "层次聚类结果"))
        self.button_kmeans.setText(_translate("MainWindow", "K-Means"))
        self.button_gmm.setText(_translate("MainWindow", "GMM"))
        self.button_hcc.setText(_translate("MainWindow", "层次聚类"))
        self.menu_1.setTitle(_translate("MainWindow", "数据"))
        self.traindata.setText(_translate("MainWindow", "Train_DATA"))
        self.testdata.setText(_translate("MainWindow", "Test_DATA"))

