# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(547, 385)
        self.label_background = QtWidgets.QLabel(Dialog)
        self.label_background.setGeometry(QtCore.QRect(-30, -10, 580, 201))
        self.label_background.setText("")
        self.label_background.setPixmap(QtGui.QPixmap("../login_picture.jpg"))
        self.label_background.setScaledContents(True)
        self.label_background.setObjectName("label_background")
        self.label_note = QtWidgets.QLabel(Dialog)
        self.label_note.setGeometry(QtCore.QRect(50, 290, 131, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_note.setFont(font)
        self.label_note.setObjectName("label_note")
        self.label_user_name = QtWidgets.QLabel(Dialog)
        self.label_user_name.setGeometry(QtCore.QRect(220, 220, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_user_name.setFont(font)
        self.label_user_name.setObjectName("label_user_name")
        self.button_login = QtWidgets.QPushButton(Dialog)
        self.button_login.setGeometry(QtCore.QRect(230, 330, 271, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.button_login.setFont(font)
        self.button_login.setAutoDefault(True)
        self.button_login.setObjectName("button_login")
        self.label_password = QtWidgets.QLabel(Dialog)
        self.label_password.setGeometry(QtCore.QRect(220, 280, 51, 21))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.label_password.setFont(font)
        self.label_password.setObjectName("label_password")
        self.label_title = QtWidgets.QLabel(Dialog)
        self.label_title.setGeometry(QtCore.QRect(100, 50, 341, 111))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.user_name_text = QtWidgets.QLineEdit(Dialog)
        self.user_name_text.setGeometry(QtCore.QRect(280, 220, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.user_name_text.setFont(font)
        self.user_name_text.setObjectName("user_name_text")
        self.password_text = QtWidgets.QLineEdit(Dialog)
        self.password_text.setGeometry(QtCore.QRect(280, 280, 221, 31))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(14)
        self.password_text.setFont(font)
        self.password_text.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_text.setObjectName("password_text")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_note.setText(_translate("Dialog", "华东理工大学"))
        self.label_user_name.setText(_translate("Dialog", "账号："))
        self.button_login.setText(_translate("Dialog", "登录"))
        self.label_password.setText(_translate("Dialog", "密码："))
        self.label_title.setText(_translate("Dialog", "<html><head/><body><p>基于大数据的长型材</p><p>人工智能算法库</p><p><br/></p></body></html>"))
